### ISSUE TITLE
cache arrays

### ISSUE THREAD

**Issue by aetsyss** [hyperoslo/Cache#103]
Hello, 

I have a simple struct like this:

struct Person: Coding {
 var name: String
...
...
}

And I made it conformable to the Coding protocol. But when I try to do this:
let persons: [Person] = [...]
cache.add("keys", object: persons) 
I get an error.

So my question is how to cache the array of object witch are conformable to the Coding protocol?

**Comment by vadymmarkov** [comment]
Hi @aetsyss It wasn't possible before, but now there is `CacheArray` struct you can use to wrap your array and cache it https://github.com/hyperoslo/Cache/pull/104
