### ISSUE TITLE
"The file “C4CA4238A0B923820DCC509A6F75849B” doesn’t exist."

### ISSUE THREAD

**Issue by Nathan187** [hyperoslo/Cache#105]
not sure why this is happening all of a sudden..had to change my code since the library was updated

**Comment by vadymmarkov** [comment]
@Nathan187 Hi! `DiskStorage` path was changed in 3.0 release, so it might be a reason why it can't access your old files.

**Comment by Nathan187** [comment]
i got it working....i was doing a .clear immediately after initialization.  every time the view displays, i want to clear the cache.   doing it like that was messing it up

thanks for the quick response!
