### ISSUE TITLE
Add a way to disable log

### ISSUE THREAD

**Issue by jdordoigne** [hyperoslo/Cache#108]
Hi,

I'm using the cache to cache data from internet (api response...).
So first I check if the needed ressource exists in cache, otherwise I tried to get it from the remote server.

The main issue is the amount of log that is generated. Each check generate a log in the debugger because the key does not exists (which is normal because the resource does not yet exists in cache) .
It's really annoying while debugging to have all this messages

Could you add a way to disable logs to avoid these unecessary stack ?

**Comment by zenangst** [comment]
@jdordoigne hey, I just made a small PR to enable/disable logging. I set the feature to be disabled by default. Hope you like it :)
