### ISSUE TITLE
i would really like to use this library

### ISSUE THREAD

**Issue by Nathan187** [hyperoslo/Cache#112]
but it seems like every other day, this error pops up

it's so damn frustrating

"No such file or directory"}}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 182

**Comment by Nathan187** [comment]
No longer an issue.  RTFM

**Comment by zenangst** [comment]
@Nathan187 hey man. glad that you solved it, mind sharing what was the issue? :)

**Comment by Nathan187** [comment]
Code not in front of me.  But from what I remember

_cache = SyncCache(named:"mycache")
_cache.clear()

I was not keeping the file on disk.  There is a parameter in the clear method that I wasn't setting to 'true'

À tout à l'heure
Envoyé de mon iPhone 6S - Megara
