### ISSUE TITLE
Coding does not work anymore

### ISSUE THREAD

**Issue by s1ddok** [hyperoslo/Cache#114]
Looks like this dirty stuff doesn't work anymore:

```swift
guard let helper = (NSClassFromString(type) as? NSCoding.Type)?.init(coder: aDecoder) else {
      return nil
    }
```

**Comment by vadymmarkov** [comment]
@s1ddok Are you using Cache with Swift 4? If yes, can you confirm it worked properly in Swift 3? `Coding` was an experimental feature that I personally never used in real world apps and my plan is to get rid of it in the the next version of `Cache` in favour of `Codable`. But for now if I want to cache structs I normally go with `JSON`.

**Comment by saoudrizwan** [comment]
@vadymmarkov any news on when the Swift 4 version will be released? I'd love to help in any way possible.

**Comment by zenangst** [comment]
@saoudrizwan ohai, we tend to wait with supporting beta software until the GM comes out (which should be around September-ish). The main reason is that we don't want to maintain two branches, if we make active development on `master`, the `swift4` branch can end up being stale pretty quickly.

**Comment by onmyway133** [comment]
@s1ddok `Coding` was merely in its early phase and is not supported any more in latest version https://github.com/hyperoslo/Cache/releases/tag/4.0.0
