### ISSUE TITLE
NSCoding warning

### ISSUE THREAD

**Issue by ened** [hyperoslo/Cache#115]
For record first:

```
/Pods/Cache/Source/Shared/DataStructures/Coding.swift:79:21: Private class 'CodingCapsule' has an unstable name when archiving via 'NSCoding'
```

Might be related to XCode9 / Swift 3.1?

**Comment by zenangst** [comment]
Hey @ened, which beta are you running? I've been using `Cache` is a bunch of projects using Xcode 9 and I haven't encountered this. Also, which version of `Cache` are you running?

**Comment by zenangst** [comment]
ping @ened :)

**Comment by zenangst** [comment]
Closing this now. feel free to re-open it if it is still an issue.

**Comment by jsonfellin** [comment]
I'm seeing this issue. I'm running Xcode 9 beta 6. I'm using 3.3.0 of Cache. Here's a screen shot:

<img width="255" alt="screen shot 2017-09-01 at 3 57 38 pm" src="https://user-images.githubusercontent.com/9867701/29973122-bb96af34-8f2e-11e7-8f75-c6351bed6175.png">

**Comment by vadymmarkov** [comment]
I think `Coding` protocol brought a lot of issues since it was introduced. We have a plan to remove it in favour of `Codable` from Swift Standard Library.

**Comment by jmoscatiello** [comment]
Is there a workaround in the mean time.

**Comment by xrelative** [comment]
Hi guys!
I have same error:
![image](https://user-images.githubusercontent.com/2634362/37832726-2e07929c-2e88-11e8-82a3-9a42d588872d.png)

Xcode 9.2
