### ISSUE TITLE
Swift 4 proposal

### ISSUE THREAD

**Issue by onmyway133** [hyperoslo/Cache#120]
- Now that Swift 4 is on the way, and `Codable` changes the game. I would like to refactor Cache to be more Swift 4 friendly. Here are my proposals
- Remove all the specialise cache, hybrid cache, sync cache, as they are confusing. Let's just have 1  type called `Storage` that supports `Codable`. Since `Codable` serialises into `Data`, things are simple, and it works with generic

```swift
let storage = Storage(directory, expiry)
storage.add<T>(object, key)
storage.object(key) as? T
storage.delete(key)
storage.deleteAll() // clear all in the directories
```

- Asynchronous is done easily by using a helper inner class, but the public API is simple

```swift
storage.async.object(key) { object as T
  // do with the object
}
```

- `Storage` itself handles memory and disk cache internally so users doesn't have to care. We can pass an option if user wants memory cache or not.

**Comment by vadymmarkov** [comment]
@onmyway133 Let's do it 🚀

**Comment by jyounus** [comment]
Awesome! I was looking at some libs that I could use for caching and I think I will be settling for this one. I will wait until you guys have updated it to Swift 4. 

Btw, regarding this:

> Storage itself handles memory and disk cache internally so users doesn't have to care. We can pass an option if user wants memory cache or not.

I'm assuming this means to allow passing in a config object when initialising? So something like:
`let storage = Storage(..., config: Config)`

Would be good if we had the freedom to define the options for the storage ourselves. :)

**Comment by onmyway133** [comment]
@jyounus Hi thanks for checking this out. I implement `Storage` with https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern in mind, so there are lots of `Storage` that get built on top of each other. You have the freedom to pretty much anything. But we decide that there should be `memory cache first, disk cache second` as this is pretty common use case. Can you tell a bit about your use case?

**Comment by jyounus** [comment]
Nice. 

I will be using it for caching API responses on disk and retrieving them if there's no internet access. The only thing I'm conscious of is to make sure that I don't keep adding to the cache, I want to make sure there's a limit for the cache (in terms of storage space on disk & the time it was last updated). 

That's it really.

**Comment by onmyway133** [comment]
@jyounus The things you mentioned is already supported by `DiskStorage`. It allows you to specify max size and expiry date. Will keep you posted when things are done 😉

**Comment by jyounus** [comment]
Awesome, looking forward to it! Thanks :D

**Comment by onmyway133** [comment]
@jyounus Hi, you can check https://github.com/hyperoslo/Cache/releases/tag/4.0.0 🎉
