### ISSUE TITLE
Swift 4 AsyncStorage is not public

### ISSUE THREAD

**Issue by zirinisp** [hyperoslo/Cache#133]
I justed ported to Swift 4 and noticed that I cannot access async functions.

Is there a reason for that. I tried to access the async methods though Storage object and I could not find any async functions.

As I understand it, you have to create a Storage object and then use it to initialise an AsyncStorage object. Once you have done that you can only access async methods. But with AsyncStorage not being public this cannot be done.

**Comment by onmyway133** [comment]
@zirinisp Hi, Cache is undergone refactoring to swift 4. We will update README to reflect the changes

**Comment by onmyway133** [comment]
@zirinisp Hi, you can check version https://github.com/hyperoslo/Cache/releases/tag/4.0.0
