### ISSUE TITLE
Linux and SPM support

### ISSUE THREAD

**Issue by LeoNavel** [hyperoslo/Cache#137]
Will be there any linux and swift package manager support? In my fork I've made some Linux changes and it looks ok (but I remove all files for iOS, WatchOS and TVOS) I preffer if you made all the important changes because I dont know how to work with cocoapod etc... If there is anything I can help with just ask. Thanks for response

**Comment by onmyway133** [comment]
@LeoNavel Hi, `Cache` works with `Cocoapods` and `Carthage` now. It can work with `SPM` but we don't have the capacity to do this at the moment. You can just copy the files that you like into your project.

We also don't have plan to support `Linux` in the foreseeable future. Hope you understand.
