### ISSUE TITLE
removeAll() leaves storage in unusable state

### ISSUE THREAD

**Issue by rvanmil** [hyperoslo/Cache#147]
Calling removeAll will delete the cache directory, but does not recreate it. This results in "The file “x” doesn’t exist." errors when adding objects to the cache afterwards.
Adding the line `try createDirectory()` to the removeAll method fixes the issue.

**Comment by onmyway133** [comment]
@rvanmil Nice catch, we will fix it 👍

**Comment by rvanmil** [comment]
I've created a pull request with a proposed fix.

**Comment by onmyway133** [comment]
@rvanmil FYI https://github.com/hyperoslo/Cache/releases/tag/4.0.1
