### ISSUE TITLE
Is there any document describing how to migrate to 4.0.0 from 3.3.0?

### ISSUE THREAD

**Issue by Jerome1210** [hyperoslo/Cache#149]
As title, I found it has big difference between 3.3.0 to 4.0.0. 
I'm wondering is there any tips to migrate to 4.0.0? 
Maybe some example how to convert Cacheable protocol to Codable or how to replace CacheArray type to current design.
Thanks.

**Comment by Jerome1210** [comment]
I think I've solved the issue, and here is the tips how I migrate from 3.3.0 to 4.0.0

1. remove Cacheable protocol and make the class/struct/enum conform to Codable
may refer to this [gist](https://gist.github.com/ahcode0919/88d5dd8607162ea8486bcd17681f2190). Typically, the Codable protocol make encode/decode data very very easy... You won't have to use NSCoding any more. may refer to the [post](https://medium.com/monitisemea/swift-4s-codable-one-last-battle-for-serialization-30ceb3ccb051) to get more infomation.
2. CacheArray<SomeClass> can be replaced by [SomeClass].self

**Comment by vadymmarkov** [comment]
Would be nice to add some kind of migration guide though. What do you think @onmyway133?

**Comment by onmyway133** [comment]
@Jerome1210 Hi, sorry for confusion. You're right about `Cachable` and `CacheArray`. You can take a look at the updated changelog here https://github.com/hyperoslo/Cache/releases/tag/4.0.0
