### ISSUE TITLE
HybridCache no longer accessible?

### ISSUE THREAD

**Issue by terenzeyuen** [hyperoslo/Cache#150]
We used to decalre like this:

cache = HybridCache("Name")

But this seems to fail at SWift 4.0? Any help?

**Comment by JoniVR** [comment]
Same here, I think the syntax changed but I can't find any documentation on how to replace it.

**Comment by wesbillman** [comment]
@terenzeyuen @JoniVR are you looking for this? https://github.com/hyperoslo/Cache/blob/master/Source/Shared/Storage/HybridStorage.swift

`HybridStorage`

**Comment by JoniVR** [comment]
@wesbillman Probably yes, thank you very much! 👍🏻 (silly I couldn't find that myself)

**Comment by terenzeyuen** [comment]
Thanks @wesbillman but the init is different now? We used to just passed the name, is this part of migration?

**Comment by wesbillman** [comment]
@terenzeyuen that I don't know. I was just browsing and saw this issue, so thought I would point out this class.

**Comment by JoniVR** [comment]
@terenzeyuen Yes, the init is different now, in the readme it explains how it works (haven't entirely figured it out yet but getting there.) 

It now has a `memoryConfig` and `diskConfig` parameter. The memory storage is for fast, temporary storage, the disk storage is a little bit slower but is persistent across launches.

I thinks it is configured as follows: 
```swift
let diskConfig = DiskConfig(name: "Floppy")
let memoryConfig = MemoryConfig(expiry: .never, countLimit: 10, totalCostLimit: 10)

let storage = try? Storage(diskConfig: diskConfig, memoryConfig: memoryConfig)
```

If I'm wrong about something feel free to correct me lol 😜

**Comment by onmyway133** [comment]
@terenzeyuen @JoniVR @wesbillman Hi, sorry for the confusion. @JoniVR is absolutely right 👍 about the new usage. In the mean time, you can take a look at the updated changelog here https://github.com/hyperoslo/Cache/releases/tag/4.0.0

**Comment by terenzeyuen** [comment]
Thanks !
