### ISSUE TITLE
Carthage – Suggestion to add in documentation

### ISSUE THREAD

**Issue by terenzeyuen** [hyperoslo/Cache#151]
Just a suggestion to add in Documentation for Carthage users. Make sure you include SwiftHash.framework in Carthage script. 

> $(SRCROOT)/Carthage/Build/iOS/SwiftHash.framework

**Comment by onmyway133** [comment]
@terenzeyuen Hi, thanks for the suggestion. I just updated version 4.0.2 https://github.com/hyperoslo/Cache/releases/tag/4.0.2. With that, you don't need to do the scripting. Just embed that framework
