### ISSUE TITLE
Apple Store submission

### ISSUE THREAD

**Issue by jdordoigne** [hyperoslo/Cache#156]
I have updated cache to version 4.0.3 and since, I can't upload my application anymore to the apple store :(
I'm using Carthage and iOS extension.

I'm having these following errors : 

```
iTunes Store Operation Failed
ERROR ITMS-90205: "Invalid Bundle. The bundle at 'Application.app/Frameworks/Cache.framework' contains disallowed nested bundles."
```

```
iTunes Store Operation Failed
ERROR ITMS-90206: "Invalid Bundle. The bundle at 'Application.app/Frameworks/Cache.framework' contains disallowed file 'Frameworks'."
```

I tried to play with Cache project configuration with no luck.

In V3 I had to manually add SwifthHash as a dependency. In the latest version the dependency seems to be added automatically. Could it be the issue?

**Comment by onmyway133** [comment]
@jdordoigne you're right, I added them automatically https://github.com/hyperoslo/Cache/pull/152 😞

**Comment by jdordoigne** [comment]
Indeed this is the issue, I have added a script to remove embedded frameworks and submission works

**Comment by onmyway133** [comment]
@jdordoigne Hi, you can check https://github.com/hyperoslo/Cache/releases/tag/4.0.4 which I removed that script and update the README
