### ISSUE TITLE
The library does not compile in Topshelf for a tvOS application

### ISSUE THREAD

**Issue by jojoman2** [hyperoslo/Cache#161]
When trying to use this library in the Topshelf in a tvOS application, the library fails to compile. The following line causes the problem:
`let application = UIApplication.shared`
The error message is: 
`'shared' is unavailable: Use view controller based solutions where appropriate instead.`

In case you are not familiar with tvOS development: The Topshelf is a target in Xcode which is used to show application content when the user has navigated to the application icon but not chosen it. More information can be found [here](https://developer.apple.com/tvos/human-interface-guidelines/overview/top-shelf/)

**Comment by jojoman2** [comment]
This was on an old version of the library. Sorry to bother yoy

**Comment by onmyway133** [comment]
@jojoman2 No worry, glad that you find `Cache` useful
