### ISSUE TITLE
Building framework using Carthage and Xcode 9.1 failed

### ISSUE THREAD

**Issue by peterz** [hyperoslo/Cache#162]
I'm trying to build framework with Carthage using the latest Xcode but it fails.

> Build Failed
> 	Task failed with exit code 65:
> 	/usr/bin/xcrun xcodebuild -project /Users/.../Carthage/Checkouts/Cache/Cache.xcodeproj -scheme Cache-iOS -configuration Release -derivedDataPath /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/Cache/4.1.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/.../Carthage/Checkouts/Cache)

I've also tried this solution: [https://github.com/Carthage/Carthage/issues/2062](url) but it's not working.

**Comment by onmyway133** [comment]
@peterz Hi, I just try running Carthage again. Here is my `Cartfile.resolved`

```
github "hyperoslo/Cache" "4.1.2"
```

Can you create an empty project and install Cache using Carthage, to see if you can replicate the issue ?

**Comment by peterz** [comment]
@onmyway133 I tried both things and I get the same issue. Here is a message from log file: 

> ** ARCHIVE FAILED **
> 
> 
> The following build commands failed:
> 	PhaseScriptExecution SwiftLint /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/Cache/4.1.2/Build/Intermediates.noindex/ArchiveIntermediates/Cache-iOS/IntermediateBuildFilesPath/Cache.build/Release-iphoneos/Cache-iOS.build/Script-BD58C3AD1CF2E9FD003F7141.sh
> (1 failure)

**Comment by onmyway133** [comment]
@peterz Hi, I can't reproduce the problem. Can you try the latest version of Carthage https://github.com/Carthage/Carthage/releases/tag/0.26.2 ?

**Comment by peterz** [comment]
@onmyway133 it seems to be working now so you can close the issue.
