### ISSUE TITLE
In-memory only caching

### ISSUE THREAD

**Issue by kirillyakimovich** [hyperoslo/Cache#164]
Hi guys,

In our app in some cases we want to use `MemoryStorage` only, but  it has internal access level.
So my first question is: do we really want to hide `MemoryStorage`, `DiskStorage`, `HybridStorage` and TypeWrapperStorage? If the answer is no - i will set up a PR providing public access to them.

We can also tweak Storage:
1. changing`init(diskConfig: DiskConfig, memoryConfig: MemoryConfig? = nil)` making it accept optional DiskConfig: `init(diskConfig: DiskConfig?, memoryConfig: MemoryConfig? = nil)`
2. provide several distinguish initializers:
`init(diskConfig: DiskConfig)`, 
`init(memoryConfig: MemoryConfig)`
`init(diskConfig: DiskConfig, memoryConfig: MemoryConfig)`

I personally prefer first solution as it will not break current API and will keep interface simple.
And if we decide to go with it there is one degenerative case, when both configs were nil's.
I can see 2 solutions as well:
1. throwing new exception(`invalidConfig`)
2. providing new internal storage(`IdleStorage`) that will always fail to cache but will conform to StorageAware
Second question is: Should we tweak Storage or should such things be done by users of the `Cache`?

I will provide PR if needed :)

**Comment by onmyway133** [comment]
@kirillyakimovich Hi, to be honest, I would use `NSCache` instead of bringing another new library just for memory cache.  What's the problem with `NSCache` that you're facing? Just want to ask a bit about the intention before we're going to implementation 😉 

The reason we made those `private` because we think those are just implementation of the library, and should not be the user's concern

**Comment by kirillyakimovich** [comment]
@onmyway133 Hi. I agree that using external library for memory cache is an overkill :)
But we're in need of configurable(by plist or backend) cache, something like:
```
enum CacheType {
    case none, memory, disk, both
}
```
And there we have nice StorageAware protocol.

**Comment by kirillyakimovich** [comment]
ping @onmyway133
