### ISSUE TITLE
Question on Expiry time

### ISSUE THREAD

**Issue by annjawn** [hyperoslo/Cache#167]
Hello there @onmyway133 again,

I have a quick question-

I am planning to use `cache` in my project to cache a `Decodable` object for 15 mins. The data is acquired through an API call that has a rate limit per 15 mins and thus I would cache it for 15 mins, and call the API again (based on some user action) if the cache has expired. For this it looks like your async methods are more appropriate, i.e. this is something I would do as soon as the user fires up the app-

```
struct friendlist: Decodable{
 let friendUID: String
}

//API Call completion block { response, data, connectionError in
 do {
       let json = try JSONDecoder().decode(friendlist.self, from: data!)
       try? storage.setObject(json, forKey: "firendList")
  } catch let jsonError as NSError {
       print("json error: \(jsonError.localizedDescription)")
  }
}...
```
Now the default expiration is 15 mins. Now based on certain user action it's time to check if a cached version of the object exists or not. If exists then use that, or else call the API again to get the fresh set of data.

```
storage.async.existsObject(ofType: friendlist.self, forKey: "firendList") { result in
  if case .value(let exists) = result, exists {
    print("Friend list in cache, so use it")
  }else{
    print("Not in cache, call API again...")
  }
}
```

Now my question is - does `existsObject` checks if the timer on an existing cache is expired? or it just checks if the object exists or not regardless of the expiration? what happens when the timer is expired and `storage.async.existsObject` is called on that object? does it throw an error or does it enters the completion block and let's me evaluate the `result` (as is shown above) and lets me make another API call. Also in this case, if the object is expired does `existsObject` automatically takes care of removing the expired object or that still needs to be done (?) using 

```
storage.async.removeExpiredObjects() { result in
  print("removal completes")
}
```

**Comment by AshleyDeng** [comment]
Good questions! I wonder what the answers are as well.
