### ISSUE TITLE
Possible issue with "expiry"

### ISSUE THREAD

**Issue by annjawn** [hyperoslo/Cache#168]
I have been trying to set a cache with a set expiry of 15 mins.  `.entry` keeps showing me a totally different expiration time-

for example at 4:15 PM i ran this

```
try? storage.setObject(
            "This is a string",
            forKey: "string",
            expiry: .date(Date().addingTimeInterval(15 * 60))
        )
```

Consecutively, this is a result I get

```
let entry = try? storage.entry(ofType: String.self, forKey: "string")
print(entry?.object)
print(entry?.expiry)

Console output-
Optional("This is a string")
Optional(Cache.Expiry.date(2017-11-21 00:22:32 +0000))
```

The expiry date should be something like `2017-11-20 04:30:32 +0000` but it's showing midnight of 21st at 12:00 AM.

**Comment by xPryds** [comment]
Isn`t  because Date() show UTC date instead of your location date?
