### ISSUE TITLE
Is there any way to get a list of keys currently stored in cache?

### ISSUE THREAD

**Issue by RamblinWreck77** [hyperoslo/Cache#169]
Hello! 

I'm trying to use cache to improve my logging setup. Basically I want to write my logs to cache as they happen and periodically upload them to my server.

To do this, it seems like I need to be able to get a list of all existing keys in the cache so my uploader can fetch them to post (and re-remove them from cache on upload success!)

So basically: 

-It's time to upload, purge all expired keys

-get list of keys

-for each key, extract payload and upload. On post success remove that key from the cache so we never double post

Is this possible with cache? Any tips?

Thanks!

**Comment by onmyway133** [comment]
@RamblinWreck77 Hi, currently we don't support this, although you can access `keys` property in `MemoryStorage`. One workaround is to have another `Storage` just for your keys information
