### ISSUE TITLE
What is cost?

### ISSUE THREAD

**Issue by tamoyal** [hyperoslo/Cache#170]
I see the param `totalCostLimit` but no explanation of cost. What does it mean?

**Comment by IgorBulyga** [comment]
Hey, @tamoyal , as the documentation says:

>   /// The maximum total cost that the cache can hold before it starts evicting objects. 0 means no limit.

That means the maximum size, in bytes, which cache object can retain in memory before it starts throwing away objects.

**Comment by MasterXval** [comment]
I believe it's actually un-used.

I've checked in the code in MemoryStorage while it's correctly set on the underlying NSCache, object added to the cache never provide any cost (which fallback to cost = 0).

Or am I missing something ?

**Comment by guoyingtao** [comment]
@MasterXval, I think you are right, it's actually un-used.
Also, I don't think it's easy to get the cost of an object since it could be any type. So I just made a pull-request to ask for removing this totalCostLimit for not confusing users.

**Comment by onmyway133** [comment]
@MasterXval Hi, both the `countLimit` and `totalCostLimit` are properly set in https://github.com/hyperoslo/Cache/releases/tag/5.0.0
