### ISSUE TITLE
ERROR: ... couldn’t be opened because there is no such file...

### ISSUE THREAD

**Issue by tamoyal** [hyperoslo/Cache#171]
I just upgraded from 3.x to `Cache (4.1.2)` and after setting up, cache gives me this error every time:

```
Error Domain=NSCocoaErrorDomain Code=260 "The file “87B84E4AE30FCAE7D4EB5BC98A7293A6” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/09447C5B-FC09-44E2-8FE0-6F73D89E9AB3/Library/Caches/ApiCache/87B84E4AE30FCAE7D4EB5BC98A7293A6, NSUnderlyingError=0x1c425ac40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

when calling the below `getCurrentUser` method:

```
static let diskConfig = DiskConfig(name: "ApiCache")
static let memoryConfig = MemoryConfig(expiry: .never, countLimit: 500, totalCostLimit: 1000)
static let storage = try? Storage(diskConfig: diskConfig, memoryConfig: memoryConfig)

static func getCurrentUser(onGet: @escaping (JSONStandard?)->()) {
    storage?.async.object(ofType: JSONStandard.self, forKey: "users/current", completion: { result in
        switch result {
        case .value(let json):
            onGet(json)
        case .error(let error):
            print(error)
        }
    })
}
```

**Comment by tamoyal** [comment]
I was confused by the API. Error just means cache miss and this error is just saying the value doesn't exist for key.

**Comment by RamblinWreck77** [comment]
I'm confused by this as well. Shouldn't the result be a StorageError type? I'm getting an unknown error type as any cast to StorageError fails

**Comment by Erumaru** [comment]
@tamoyal @RamblinWreck77 did you guys find out what causes the problem?

**Comment by martindufort** [comment]
I'm running into the same issue....
After investigation I found that when you are trying to retrieve an object from the disk cache, the Cache is looking for a specific file on disk. 

To do so, it creates a specific unique filename based on the key provided. 
If the file does not exists, the URL init method raises an exception 
That exception is throw right up to the caller. 

In DiskStorage.swift (line 61)

```
    let filePath = makeFilePath(for: key)
-->    let data = try Data(contentsOf: URL(fileURLWithPath: filePath))
``` 
DiskStorage is not wrapping that exception into a `StorageError.notFound` error as expected.

My solution is to check for object existance first and then retrieve from cache if it exists. 
Something like: 
```
let objectExist = try anAccount.dataCache!.existsObject(forKey: id)
if (objectExist) {
	self.data = try anAccount.dataCache!.object(forKey: id)
         // ....
}
```
