### ISSUE TITLE
Carthage fails to build (Xcode 9.2, Carthage 0.27.0, Cache 4.1.2)

### ISSUE THREAD

**Issue by kharmabum** [hyperoslo/Cache#173]
See https://github.com/hyperoslo/Cache/issues/162

> The following build commands failed:
> 	PhaseScriptExecution SwiftLint /Users/foustjc/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/Cache/4.1.2/Build/Intermediates.noindex/ArchiveIntermediates/Cache-iOS/IntermediateBuildFilesPath/Cache.build/Release-iphoneos/Cache-iOS.build/Script-BD58C3AD1CF2E9FD003F7141.sh
> 

[carthage-xcodebuild.IuCJfy.log](https://github.com/hyperoslo/Cache/files/1627578/carthage-xcodebuild.IuCJfy.log)

**Comment by onmyway133** [comment]
@kharmabum Hi, sorry for late response. If seems this is due to inconsistent SwiftLint rule between Cache and your project

**Comment by onmyway133** [comment]
@kharmabum Hi I removed Swiftlint in the new version https://github.com/hyperoslo/Cache/releases/tag/5.2.0
