### ISSUE TITLE
Shouldn't the default cache folder be /library or /documents not /library/caches?

### ISSUE THREAD

**Issue by RamblinWreck77** [hyperoslo/Cache#179]
So I've been chasing a weird issue and I think I've gotten to the bottom of it. My app launches in the background periodically and I need to recover user data. After some logging it appeared my users were being logged out way too often/not having user credentials frequently. 

So keychain periodically (~5%) of the time fails in the background (longstanding iOS issue), so I store a backup copy in cache to catch it. 

Thing is, periodically *cache* fails too (with a not-found error for a user that definitely exists, and successfully wrote some info to disk)

I discovered that the default directory is Library/Caches, and according to:

https://stackoverflow.com/questions/7155964/will-application-home-library-caches-be-clear-on-app-update

and various other places iOS can periodically clear those files. 

This seems counter-intuitive as I would expect most devs to expect a .never expiry to not be at risk of deletion from the OS itself. 

All in all it's not a big deal to switch to /Documents (it's nice that this will be backed up by itunes/icloud... library/caches is not!) I am wondering if a change to the default location wouldn't make sense. 

Thanks for such a great tool!

Edit: For those who find this later, the correct folder for this is Library/Application Support. I will update this post if moving to this folder solves my issue. I have a build rolling out now that uses the new location so I will see if this fixes my primary issue.

**Comment by IgorBulyga** [comment]
@RamblinWreck77  Hi!Use Documents directory to store cache files not good idea, because if you will enable iTunes File Sharing Option in you application user will see your caches files. However apple provided another directory for storing application related files which is also will be backed up in iCloud - Library/Application Support. Just create here folder for your data and store them.

**Comment by john1452** [comment]
ah this seems to be same issue that I am having https://github.com/hyperoslo/Cache/issues/180 
I expected the .never expiry to never delete the folder. Maybe the default path should change?

Question: Library/Application safe to store user sensitive information? Such user phone number, email address etc?

**Comment by IgorBulyga** [comment]
@RamblinWreck77 Yes, like Apple Documentation [says](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html)

> Put app-created support files in the Library/Application support/ directory. In general, this directory includes files that the app uses to run but that should remain hidden from the user. This directory can also include data files, configuration files, templates and modified versions of resources loaded from the app bundle. Remember that files in Documents/ and Application Support/ are backed up by default.

@john1452 I suppose it would be safe BUT it would be better to store user sensitive data in keychain.

**Comment by RamblinWreck77** [comment]
Update: I've had this fix out for ~2 weeks now and am not seeing a drop off in background file-not-found.

I'm at a loss for what could be causing this...

**Comment by onmyway133** [comment]
@RamblinWreck77 Hi, I 've made a refactoring here https://github.com/hyperoslo/Cache/pull/189 and address your issue. You can still use DiskConfig to customise directory path, and from now on, document directory is used by default

**Comment by IgorBulyga** [comment]
@onmyway133 Hi, I suppose it is not good idea. Because Documents directory is used for user information and it could be visible to user if application supports iTunes File Sharing, besides now cache folder will be changed folder for applications which are using library and they will recache everything what was cached. 

Maybe it would be better leave cache directory by default and who will not want use it could change it in config?

**Comment by onmyway133** [comment]
@IgorBulyga After discussion, I think you're right. We will use Cache directory for now
