### ISSUE TITLE
The file "" couldn’t be opened because there is no such file

### ISSUE THREAD

**Issue by john1452** [hyperoslo/Cache#180]
Hi I am getting some strange errors. It seems the cache is clearing it self after some time..

The error i receive is the following.

The file “48D236928EDB4A0D5601D267C5182EEB” couldn’t be opened because there is no such file
The cache it self clearer knows the file it wants to access but for some reason the file is deleted.
Any ideas when this can occur? Here is the initialization of my storage.

> 
>  func loadStorage(){
> 
>         do {
>             let diskConfig = DiskConfig(name: storageDiskConfig,expiry: .never,protectionType: .complete)
>             self.storage = try Storage(diskConfig: diskConfig)
> 
>         } catch {
>             self.logger.information(source, "Init", "Failed to initialise storage instance error: \(error.localizedDescription). ")
>         }
>     }
>

**Comment by onmyway133** [comment]
@john1452 Hi, do you specify `expiry`? That could cause objects to be cleared after some time

**Comment by Erumaru** [comment]
@onmyway133 I don't specify expiry, but often my cache user account becomes nil and it leads to logout him from account. Is it known issue? May be I'm doing something wrong? I've heard that creating new variables in model, which is cached leads it to become nil, if I don't process it properly. Can you please give me some links related to that one, please.

**Comment by tguidon** [comment]
I'm seeing this issue quite a bit now. My storage is being set as a global variable (maybe a problem here?) and with an expirary of 8 hours. After 2-4 hours of the app in the background, the user comes back to the app and sees that same _long string filename_ can not be opened error.

Is there a best practice for defining storage?

Also, I am using Cache in a private Pod as an SDKs caching layer if that helps.

**Comment by Erumaru** [comment]
Hi @tguidon did you find out what was the problem? I still can't solve it and using workarounds :(

**Comment by tguidon** [comment]
@Erumaru I was never able to find out what the issue was. My workaround was to make two storage containers. One for arrays of data and one for objects.

What workaround are you using?

**Comment by Erumaru** [comment]
@tguidon thank you for response, my cached user sometimes become nil and I have to update it from backend when this happens at app start. I store token in Keychain.
