### ISSUE TITLE
setObject Thread Problem

### ISSUE THREAD

**Issue by mcfans** [hyperoslo/Cache#181]
The code below will lead to dead lock,because in the setObjectmethod it will try to encode this class in a  sync queue,but in the encodemethod,the user try to set something in that sync queue.

    class DeadLock: Codable{
        ///
        func encode(to encoder: Encoder) throws {
            try storage.setObject("", forKey: "Something")
        }
    }
    try? storage.setObject(DeadLock(), forKey: "Some other")

**Comment by vadymmarkov** [comment]
Hey @mcfans! Yes, it will happen in your example, but why would you need to do that?

**Comment by mcfans** [comment]
Actually I am trying to encode the key for the data that I want to save , not the data itself.The  Codable implementation is not just for this Cache framework, for some reason, that encoded data must be small.So I try to save the large data with the Cache, and encode the generated key to the encoder, then save the encoded data with the Cache.Actually, in my case,that data is from an image, after reading your documentation,I used the ImageWrapper to solve this issue. But I think you guys need to know this if you don’t. My English is poor,I hope I made my statement clearly, thanks a lot.

**Comment by vadymmarkov** [comment]
In this case I would just do it a bit differently: save `Codable` object at first and then save the generated key (not in `encode` function). The current implementation of `Cache` is not suitable for those kind of nested operations. This example looks more like an edge case to me. But thanks for you feedback @mcfans 😉
