### ISSUE TITLE
Object Life Cycle in Storage ?

### ISSUE THREAD

**Issue by wassimseif** [hyperoslo/Cache#185]
From the documentation, there are 

`MemoryConfig` & ` DiskConfig`. So I guess that there is an option for in memory temporary storage?

I have this class
```
class CacheService {
    
    let diskConfig = DiskConfig(name: "MyApp")
    let memoryConfig = MemoryConfig(expiry: .never, countLimit: 10, totalCostLimit: 10)
    
    let diskStorage : Storage?
    
    init(){
        diskStorage = try? Storage(diskConfig: diskConfig, memoryConfig: memoryConfig)   
    }
    
    // I want this to persist across launches
    func save(user : User){
        try? self.diskStorage?.setObject(user , forKey: "user")
    }

    func save(food : Food){
        try? self.diskStorage?.setObject(food , forKey: "food")
    }
}
```
Is there a way to save the `Food` object to memory and be automatically deleted across launches ?

Also, the life cycle of the object saved to storage is not very clear in the documentation

**Comment by onmyway133** [comment]
@wassimseif Hi, if you want just memory, you can use just `MemoryStorage`, which are exposed publicly in Cache 5.0, or you can use just `NSCache`
