### ISSUE TITLE
Cache Expiry .seconds bug

### ISSUE THREAD

**Issue by gabors** [hyperoslo/Cache#186]
Recently I found that when saving a Codable into a cache that is configured to use Expiry .seconds() will never make the cache item expire. Every time I fetch an entry from the cache the expiry.date shows the current date + seconds, and therefore isExpired is always false.

When I save using the Expiry .date() entries expire as expected.

**Comment by gabors** [comment]
EDIT: even with saving to cache with .date() Expiry some of the API behave inconsistently.

Here is my testing: 

myCache.entry(ofType: String.self, forKey: key) would find the entry in the cache (unless I just called removeExpiredObjects()) and the entry would correctly show isExpired as true.

OTH, when I call myCache.existsObject(ofType: String.self, forKey: key) this would return true, which is unexpected.

ALSO! calling myCache.object(ofType: String.self, forKey: key) also finds the value in the cache even though it is expired. Very unexpected.

**Comment by onmyway133** [comment]
@gabors Hi, I wonder if this fixes your issue https://github.com/hyperoslo/Cache/pull/176 ?

**Comment by miaoruiyuan** [comment]
@onmyway133 the same problem for me ,you fix it ?
