### ISSUE TITLE
Store and Fetch an array

### ISSUE THREAD

**Issue by sylvan-d-ash** [hyperoslo/Cache#188]
I would like to know how to store and subsequently fetch an array. I've got the following models:

    struct World: Codable {
        var regions: [Region]
    }
    
    struct Region: Codable {
        var name: String
        var numberOfCountries: Int
        
        /// specify the keys in the JSON from the API
        private enum CodingKeys: String, CodingKey {
            case name = "regionName"
            case numberOfCountries = "nrCountries"
        }
        
        public init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: CodingKeys.self)
            let number = try values.decode(String.self, forKey: .numberOfCountries)
            
            numberOfCountries = Int(number) ?? 0
            name = try values.decode(String.self, forKey: .name)
        }
    }

I'm saving the `World` info like:

    let regions = [Region(name: "Europe", numberOfCountries: 21), Region(name: "Asia", numberOfCountries: 54)]
    let world = World(regions: regions)
    try self.storage?.setObject(world, forKey: "Constants.World")

And trying to fetch this data later on like:

    do {
        let world = try storage.object(ofType: World.self, forKey: "Constants.World")
    } catch {
        print("\(error.localizedDescription)")
    }

The saving seems to work OK, but I get the following error whenever I try to fetch the data from the cache: `The data couldn’t be read because it isn’t in the correct format.`

Any idea what I could be doing wrong? Or how should I save the above data?

**Comment by onmyway133** [comment]
@sylvan-d-ash Hi, when you load, can you try

```swift
let world = try storage.object(ofType: [World].self, forKey: "Constants.World")
```

Basically, use `[World].self` instead of `World.self`

**Comment by markhao** [comment]
Hi @sylvan-d-ash! Did you figure out what went wrong?

**Comment by sylvan-d-ash** [comment]
@markhao yes, I did. I should have commented about it here, because I now don't remember the problem clearly, but it had to do with the `numberOfCountries` being an `int`. I resolved it by changing it to a `string`.

I'm guessing that adding an `encode` function to deal with the `int` value would be another way to resolve it...but not sure about this.

**Comment by bhanuMatta** [comment]
@onmyway133 ,@sylvan-d-ash  -  Can you show how you created the Storage initializer function. When we are creating the Storage class init method it also asks for Transformer type.

 let diskConfig = DiskConfig(
            name: "GatherCache",
            expiry: .date(Date().addingTimeInterval(2*86400)),
            maxSize: 1000000 * 50,
            directory: try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask,
                                                    appropriateFor: nil, create: true).appendingPathComponent("MyPreferences"),
            protectionType: .complete
        )
        
        let memoryConfig = MemoryConfig(
            expiry: .date(Date().addingTimeInterval(2*60)),
            countLimit: 50,
            totalCostLimit: 50
        )
        
      let storage = try? Storage(
          diskConfig: diskConfig,
          memoryConfig: memoryConfig,
          transformer: TransformerFactory.forCodable(ofType: User.self) // Storage<User>
        )

Here my User is. - 
struct User :  Codable {
    let firstName: String
    let lastName: String
    
    enum CodingKeys: String, CodingKey {
        case firstName = "first_name"
        case lastName = "last_name"
    }
}

But what i want to achieve is that  , i want to cache  a array of [User] . How do i do that , do I need to change my Storage init method .

**Comment by 3lvis** [comment]
Hi @bhanuMatta, sorry for the late reply, where you able to resolve your issue?
