### ISSUE TITLE
New transformer parameter

### ISSUE THREAD

**Issue by vburojevic** [hyperoslo/Cache#192]
```
let diskConfig = DiskConfig(name: "Floppy")
let memoryConfig = MemoryConfig(expiry: .never, countLimit: 10, totalCostLimit: 10)

let storage = try? Storage(
  diskConfig: diskConfig, 
  memoryConfig: memoryConfig, 
  transformer: TransformerFactory.forCodable(ofType: User.self) // Storage<User>
)
```

Docs indicate to have a separate instance of storage for every type in the new version, why?
In the previous version, I used one storage to store all Codable entities, not sure how to migrate it now...

**Comment by vburojevic** [comment]
Hey! Thanks for a quick answer!

Hmm, not sure I get it. `transformCodable` still requires a type to be defined.

Now I have something like this, and just store everything that's Codable into it:
```
private let _storage: Storage = {
        let diskConfig = DiskConfig(name: "NetworkCache")
        let memoryConfig = MemoryConfig(expiry: .never)
        
        let storage = try! Storage(diskConfig: diskConfig, memoryConfig: memoryConfig)
        
        return storage
    }()
```

I would preferably have something like this now (but can't pass Codable as type now of course, this is just to illustrate):

```
let diskConfig = DiskConfig(name: "Floppy")
let memoryConfig = MemoryConfig(expiry: .never, countLimit: 10, totalCostLimit: 10)

let storage = try? Storage(
  diskConfig: diskConfig, 
  memoryConfig: memoryConfig, 
  transformer: TransformerFactory.forCodable(ofType: Codable.self) // Storage<Codable>
) 
```

I guess one way would be to have TransformerFactory return instance of TransformerFactory.data, but I'll have to deserialize every Codable struct myself to data before saving it to storage?

Because I currently have something like this:
```
func store<T: Codable>(_ data: T, forURL URL: URL) throws {
        try _storage.setObject(data, forKey: URL.absoluteString)
    }
```

Maybe I am missing something though.

**Comment by evermeer** [comment]
Initially I also was confused. I was using Cache as a generic mechanism in my network library. So the initialization cannot be done with a specific type. I now initialize the Storage with a dummy transformer and in the code that gets and sets values I initiate the transformer in the correct type.

So my cashing code now looks like this:
```
    public static func doCashableApiRequest<T: Codable>(_ method: String, cacheSeconds: TimeInterval = 7200, onFailure: @escaping () -> Void, _ onSuccess: @escaping (T?) -> Void) {
        if let object = try? MyApi.cache?.transformCodable(ofType: T.self).object(forKey: method) {
            if let object: T = object {
                onSuccess(object)
                return
            }
        }
        
        doApiRequest(method, onFailure: onFailure) { (object: T?) in
            if object != nil {
                try? MyApi.cache?.transformCodable(ofType: T.self).setObject(object!, forKey: method, expiry: .date(Date().addingTimeInterval(cacheSeconds)))
            }
            onSuccess(object)
        }
    }
```

**Comment by onmyway133** [comment]
@vburojevic Hi, you can't do this `TransformerFactory.forCodable(ofType: Codable.self)` as protocol can't conform to itself, a concrete type needs to be specified. 
@evermeer Thanks for the answer, that's also something we would like to add, to build on top the newly introduced generic Storage

**Comment by vburojevic** [comment]
@onmyway133 yes I know, I mentioned that this was just an illustration.
So Dummy transformer is the only way for now?

**Comment by onmyway133** [comment]
@vburojevic yeah, to support multiple types, UIImage, Data, custom types, not just Codable. I could make something call `CodableStorage` to transform Storage under the hood, now sure if you like that idea ?

**Comment by vburojevic** [comment]
Seems cool!

**Comment by Erumaru** [comment]
@onmyway133 Hello, when will u release this feature? :)

**Comment by ToroLiu** [comment]
I don't like 3rd `transformer` parameter. Generally, I use cache for a distinct goal, not a distinct codable class. It makes codes worse now. I prefer version 4.2.0.

**Comment by ysangmok** [comment]
Was there a change to this feature? I'm having the same issue as everyone, having initialization done with specific type makes it less generic for me.

**Comment by trevinwisaksana** [comment]
Removing this library from our app. Next time when you want to make changes this like this, you might as well create a different library for a different purpose.
