### ISSUE TITLE
Playground files outdated

### ISSUE THREAD

**Issue by fassko** [hyperoslo/Cache#193]
Both Playground files _SimpleStorage_ and _Storage_ are outdated. I think it's working with previous Cache version.

I was able to update _SimpleStorage_ playground. But _Storage_ playground has mixed data into one storage. Is this still supported?

**Comment by onmyway133** [comment]
@fassko Hi, thanks for reporting. Can you check `master` again, I just updated all the Playground files

**Comment by fassko** [comment]
@onmyway133 Yes, works like a charm now. Thanks!
