### ISSUE TITLE
Crash when reading object

### ISSUE THREAD

**Issue by pmiotto** [hyperoslo/Cache#194]
Crashed on Xcode 9.3.1, swift 4.

Saves correctly but crashes when reading back the object. See log below

* thread #1, queue = 'Cache.SyncStorage.SerialQueue', stop reason = breakpoint 3.1
    frame #0: 0x000000010931b820 libswiftCore.dylib`swift_willThrow
  * frame #1: 0x0000000107e37718 Cache`MemoryStorage.entry<A>(type=0x0000000113ad2ff0, key="api-server-config", self=0x00000001c0673d40) at MemoryStorage.swift:24
    frame #2: 0x0000000107e25284 Cache`HybridStorage.entry<A>(type=0x0000000113ad2ff0, key="api-server-config", self=0x00000001c043d240) at HybridStorage.swift:17
    frame #3: 0x0000000107e25e40 Cache`protocol witness for StorageAware.entry<A>(ofType:forKey:) in conformance HybridStorage at HybridStorage.swift:0
    frame #4: 0x0000000107e3fa40 Cache`TypeWrapperStorage.entry<A>(type=0x0000000105cae230, key="api-server-config", self=0x00000001c0674280) at TypeWrapperStorage.swift:16
    frame #5: 0x0000000107e40660 Cache`protocol witness for StorageAware.entry<A>(ofType:forKey:) in conformance TypeWrapperStorage at TypeWrapperStorage.swift:0
    frame #6: 0x0000000107e3da50 Cache`closure #1 in SyncStorage.entry<A>(entry=nil, self=0x00000001c0674500, type=0x0000000105cae230, key="api-server-config") at SyncStorage.swift:20
    frame #7: 0x0000000107e3dbb0 Cache`partial apply for closure #1 in SyncStorage.entry<A>(ofType:forKey:) at SyncStorage.swift:0
    frame #8: 0x0000000107e3dbe0 Cache`thunk for @callee_guaranteed () -> (@error @owned Error) at SyncStorage.swift:0
    frame #9: 0x0000000107e3dc94 Cache`partial apply for thunk for @callee_guaranteed () -> (@error @owned Error) at SyncStorage.swift:0
    frame #10: 0x00000001096c5574 libswiftDispatch.dylib`closure #1 () -> () in closure #1 (() throws -> A) -> () in (extension in Dispatch):__ObjC.DispatchQueue.(_syncHelper in _F417D752D2C4E9330E1C700411CE0C6A)<A>(fn: (() -> ()) -> (), execute: () throws -> A, rescue: (Swift.Error) throws -> A) throws -> A + 96
    frame #11: 0x00000001096bed7c libswiftDispatch.dylib`reabstraction thunk helper from @callee_guaranteed () -> () to @callee_unowned @convention(block) () -> () + 36
    frame #12: 0x0000000109a9545c libdispatch.dylib`_dispatch_client_callout + 16
    frame #13: 0x0000000109aa2d50 libdispatch.dylib`_dispatch_queue_barrier_sync_invoke_and_complete + 120
    frame #14: 0x00000001096cbbcc libswiftDispatch.dylib`partial apply forwarder for @nonobjc  + 96
    frame #15: 0x00000001096c5404 libswiftDispatch.dylib`(extension in Dispatch):__ObjC.DispatchQueue.(_syncHelper in _F417D752D2C4E9330E1C700411CE0C6A)<A>(fn: (() -> ()) -> (), execute: () throws -> A, rescue: (Swift.Error) throws -> A) throws -> A + 208
    frame #16: 0x00000001096c5a34 libswiftDispatch.dylib`(extension in Dispatch):__ObjC.DispatchQueue.sync<A>(execute: () throws -> A) throws -> A + 172
    frame #17: 0x0000000107e3d710 Cache`SyncStorage.entry<A>(type=0x0000000105cae230, key="api-server-config", self=0x00000001c0674500) at SyncStorage.swift:19
    frame #18: 0x0000000107e3ee90 Cache`protocol witness for StorageAware.entry<A>(ofType:forKey:) in conformance SyncStorage at SyncStorage.swift:0
    frame #19: 0x0000000107e3b810 Cache`Storage.entry<A>(type=0x0000000105cae230, key="api-server-config", self=0x00000001c00d1170) at Storage.swift:46
    frame #20: 0x0000000107e3bf58 Cache`protocol witness for StorageAware.entry<A>(ofType:forKey:) in conformance Storage at Storage.swift:0
    frame #21: 0x0000000107e3c5a0 Cache`StorageAware.object<A>(type=<unavailable>, key="api-server-config", self=0x00000001c00d1170) at StorageAware.swift:58
    frame #22: 0x0000000104e076ac MaccasAtMonopoly`DataManager.serverConfig.getter(self=<unavailable>) at DataManager.swift:29
    frame #23: 0x0000000104ddc05c MaccasAtMonopoly`MenuPagesViewController.getViewControllerFor(type=<unavailable>, self=<unavailable>) at MenuPagesViewController.swift:107
    frame #24: 0x0000000104ddb1b4 MaccasAtMonopoly`closure #2 in MenuPagesViewController.viewDidLoad($0=<unavailable>, self=<unavailable>) at MenuPagesViewController.swift:82
    frame #25: 0x0000000104ddb234 MaccasAtMonopoly`thunk for @callee_guaranteed (@unowned MenuPagesViewController.PageType) -> (@owned UIViewController, @error @owned Error) at MenuPagesViewController.swift:0
    frame #26: 0x0000000104ddb2f8 MaccasAtMonopoly`partial apply for thunk for @callee_guaranteed (@unowned MenuPagesViewController.PageType) -> (@owned UIViewController, @error @owned Error) at MenuPagesViewController.swift:0
    frame #27: 0x000000010923a918 libswiftCore.dylib`function signature specialization <Arg[0] = Owned To Guaranteed> of (extension in Swift):Swift.Collection.map<A>((A.Element) throws -> A1) throws -> Swift.Array<A1> + 684
    frame #28: 0x0000000109163310 libswiftCore.dylib`merged (extension in Swift):Swift.Sequence.map<A>((A.Element) throws -> A1) throws -> Swift.Array<A1> + 24
    frame #29: 0x000000010907c7a0 libswiftCore.dylib`(extension in Swift):Swift.Collection.map<A>((A.Element) throws -> A1) throws -> Swift.Array<A1> + 20
    frame #30: 0x0000000104ddae6c

**Comment by pmiotto** [comment]
Hi, Yes it was just a swift error breakpoint. Closing issue now.

**Comment by 814349837** [comment]
> @pmiotto Hi, I see `swift_willThrow`, do you have Swift Error breakpoint set in Xcode? Just want to confirm this is an Error throwing and not crash

How can I ignore this swift error breakpoint？
