### ISSUE TITLE
There is a problem with the use of duplicate names with Firebase.

### ISSUE THREAD

**Issue by ymkim50** [hyperoslo/Cache#199]
I am using Firebase and I am interested in the functionality of Cache and want to apply it to our project.
However, there is a naming service named Storage in the Firebase, causing a conflict with the Cache name.

Is there a way to solve this?
Do you have any plans to add a special prefix to your project, though it may be difficult.

Thank you for your good projects.

**Comment by onmyway133** [comment]
@ymkim50 Hi, can you specify `Firebase.Storage` and `Cache.Storage` and see if it works for you?
