### ISSUE TITLE
Pod sucks.

### ISSUE THREAD

**Issue by RamonGilabert** [hyperoslo/Cache#2]
As I see it now, the pod sucks.

**Comment by richardoti** [comment]
How about being more descriptive in opening new issues, @RamonGilabert  ?

**Comment by RamonGilabert** [comment]
Dude. We are kidding.

![sarcasm-meme-face-3](https://cloud.githubusercontent.com/assets/6138120/10197561/8ee50c34-6798-11e5-9ff6-df84b8590c12.png)

**Comment by RamonGilabert** [comment]
:open_mouth:
