### ISSUE TITLE
Feature request: observation

### ISSUE THREAD

**Issue by RomainBoulay** [hyperoslo/Cache#200]
Hey there!

First, congrats on delivering `Cache`, it seems to be a very well built and appreciated library. I'm working for SoundCloud, and we are considering using your library in our iOS app. Although, before we get to this point, I would have a couple of questions if you don't mind!

There's a feature we probably would like to see in our caching layer: the ability to notify external observers that something changed. By changed, I mean:
- a key was modified (i.e. edition or removal)
- same goes on a store level: a key is added, edited or removed

Do you think that's something you would like to feature in your library? If so, would you build this yourself? Or would you expect a pull request? 

Thanks in advance for you reply!

Cheers,
Romain.

**Comment by vadymmarkov** [comment]
Hey @RomainBoulay! I think it's a nice feature to have. We could add it to our backlog and build when we get time, but a pull request is more than welcome as well, especially if you don't want to wait. Could you describe how you see the public API?

**Comment by RomainBoulay** [comment]
Hey @vadymmarkov! 

Thanks for your positive answer, that sounds very good!
Regarding the public API, I've written something quickly:

```swift

import Foundation

//: Types of change

enum StoreChange {
    case addition, deletion
}

enum KeyChange<T> {
    case edition(before: T, after: T)
    case deletion
}

//: Observers

protocol StoreObserver {
    func didObserve(change: StoreChange)
}

protocol KeyObserver {
    func didObserve<T>(change: KeyChange<T>, forKey key: String)
}

//: Registers (typically implemented by the store. All input `observer` parameters must be retained weakly)

protocol KeyObserverRegister {
    func register(observer: KeyObserver, forKey key: String)
    func deregister(observer: KeyObserver, forKey key: String)
    func deregisterAll()
}

protocol StoreObserverRegister {
    func register(observer: StoreObserver)
    func deregister(observer: StoreObserver)
    func deregisterAll()
}

```

Not sure if that's correct/perfect, it's a first draft but I hope it gives you the kind of behaviour we'd like.

Regarding the implementation, I can't promise if we'll issue a PR... but if we have the time and capacity, we'll happily do it!

Cheers!

**Comment by vadymmarkov** [comment]
Hi @RomainBoulay and thanks for the great description. On the store level, do you want to be notified about every deletion in the case when functions like `removeAll` and `removeExpiredObjects` are called?

**Comment by RomainBoulay** [comment]
Hey @vadymmarkov, 

Thanks for the reply.
You're right! Your proposal sounds much better. 

Romain.

**Comment by kharmabum** [comment]
This issue can be closed as #201 was merged.

**Comment by kharmabum** [comment]
@RomainBoulay did y'all end up using this library in your app. If not, what did you end up going with?

**Comment by RomainBoulay** [comment]
@kharmabum not yet! We are in the middle of a large refactoring that aims to separate the data acquisition and storage logic behind layer(s). After this project is done, we will be free to use any other solution, your library being on top of our list at the moment!
