### ISSUE TITLE
[question] Why Entry's meta is not object?

### ISSUE THREAD

**Issue by wata** [hyperoslo/Cache#203]
Due to meta's dictionary, I need a parser...

```swift
// My parser
private struct EntryMeta {

    let filePath: String

    private let filePathKey = "filePath"

    init?(_ meta: [String: Any]?) {
        guard let filePath = meta?[filePathKey] as? String else {
            return nil
        }
        self.filePath = filePath
    }
}
```

**Comment by wata** [comment]
@vadymmarkov Thank you for reply.

Yes.

Because I would like to cache `AVURLAsset`.

```swift
static func video(forKey key: String) -> AVURLAsset? {
    do {
        let entry = try storage.transformData().entry(forKey: key)
        guard let filePath = EntryMeta(entry.meta)?.filePath else { // <= This issue
            return nil
        }
        return AVURLAsset(url: URL(fileURLWithPath: filePath))
    } catch let error {
        log.error(error)
        return nil
    }
}
```

However, as another issue, in order to play cached `AVURLAsset`, extensions (mp4, etc ...) are necessary... The current filePath is ".../XXX", but in order to actually play it needs to be ".../XXX.mp4", right?

Should I make another issue?

**Comment by wata** [comment]
[Disk](https://github.com/saoudrizwan/Disk) allows file extensions.

> If you're trying to save data like .mp4 video data for example, then Disk's methods for Data will help you work with the file system to persist all data types.
>
> let videoData = Data(contentsOf: videoURL, options: [])
>
> try Disk.save(videoData, to: .documents, as: "anime.mp4")
>
> let retrievedData = try Disk.retrieve("anime.mp4", from: .documents, as: Data.self)

https://github.com/saoudrizwan/Disk#data

**Comment by vadymmarkov** [comment]
@wata Yes, it looks like another issue for me 😉

**Comment by wata** [comment]
I created another issue for file extensions issue #204
