### ISSUE TITLE
Can't play the video that load from the cached filePath

### ISSUE THREAD

**Issue by wata** [hyperoslo/Cache#204]
I would like to cache AVURLAsset.

However, in order to play cached AVURLAsset, file extensions (mp4, etc ...) are necessary... The current filePath is ".../XXX", but in order to actually play it needs to be ".../XXX.mp4"...

```swift
static func video(forKey key: String) -> AVURLAsset? {
    do {
        let entry = try storage.transformData().entry(forKey: key)
        guard let filePath = EntryMeta(entry.meta)?.filePath else {
            return nil
        }
        return AVURLAsset(url: URL(fileURLWithPath: filePath)) // <= Can't play this AVURLAsset
    } catch let error {
        log.error(error)
        return nil
    }
}
```

Are there any good ideas?

**Comment by wata** [comment]
[Disk](https://github.com/saoudrizwan/Disk) allows file extensions.

> If you're trying to save data like .mp4 video data for example, then Disk's methods for Data will help you work with the file system to persist all data types.
>
> let videoData = Data(contentsOf: videoURL, options: [])
>
> try Disk.save(videoData, to: .documents, as: "anime.mp4")
>
> let retrievedData = try Disk.retrieve("anime.mp4", from: .documents, as: Data.self)

https://github.com/saoudrizwan/Disk#data

**Comment by vadymmarkov** [comment]
Please test that it works as expected in https://github.com/hyperoslo/Cache/releases/tag/5.1.0. CocoaPods' `pod trunk push` doesn't work for some reason, but I'll try later.

**Comment by wata** [comment]
It works fine!
I appreciate your wonderful work.
