### ISSUE TITLE
Cache removed automatically when storage is full?

### ISSUE THREAD

**Issue by wengkeong94** [hyperoslo/Cache#209]
hey,

Currently I have a working app that has auto login feature, Im using SyncHybridCache to store necessary information for this feature to work. But apparently some users are complaining that their app is unable to auto login and redirected at the landing page (page where user supposed to log in). I checked through out the codes and I believed that Cache might have remove information when the storage is full? I would like to know if that might happen.

The version I am using is 2.1.
Is there a way where I can store them and won't get removed automatically when storage is full, if this issue occurs.

Thanks.

**Comment by toddgower-hiatus** [comment]
@wengkeong94  I see this was closed without an answer. Did you ever figure this out? I'm having a very similar issue (i have session info cached, and check it on app startup but I'm seeing inconsistent results when opening the app).

**Comment by 3lvis** [comment]
As far as I know this is regular iOS behaviour, the cache is used as a backup for faster download, shouldn't be used as a persistent storage. When the device is full iOS wipes out the cache, not much we can do about it.
