### ISSUE TITLE
XCode 10 GM and Swift 4.2 fails to build

### ISSUE THREAD

**Issue by jlaws** [hyperoslo/Cache#212]
/Users/joelaws/Workspace/kratos/Pods/Cache/Source/iOS/UIImage+Extensions.swift:26:9: 'UIImagePNGRepresentation' has been replaced by instance method 'UIImage.pngData()'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIImagePNGRepresentation:2:13: 'UIImagePNGRepresentation' was obsoleted in Swift 3
/Users/joelaws/Workspace/kratos/Pods/Cache/Source/iOS/UIImage+Extensions.swift:27:9: 'UIImageJPEGRepresentation' has been replaced by instance method 'UIImage.jpegData(compressionQuality:)'
/Users/joelaws/Workspace/kratos/Pods/UIKit.UIImageJPEGRepresentation:2:13: 'UIImageJPEGRepresentation' was obsoleted in Swift 3

**Comment by doctorcolinsmith** [comment]
This fix is needed downstream to also get Imaginary and Lightbox working in Swift 4.2 as well.

**Comment by rizwan95** [comment]
#214 I have fixed the issue and you can find the fix here. Meanwhile, I have submitted a pull request to the main branch.

**Comment by onmyway133** [comment]
@rizwan95 👍

**Comment by onmyway133** [comment]
@jlaws @doctorcolinsmith @rizwan95 Hi, sorry for the delay. I just pushed new version https://github.com/hyperoslo/Cache/releases/tag/5.2.0

**Comment by jlaws** [comment]
Works great, thank you!
