### ISSUE TITLE
Can't get entry from cache second time

### ISSUE THREAD

**Issue by Recouse** [hyperoslo/Cache#219]
I can't get an entry from the cache when I do it twice or more in a row until I'll dismiss view controller. But it gets an entry from the cache first time when I'm using this method.

Using this method:
```swift
let entry = try? storage.entry(forKey: "my key")
```

**Comment by fremaksim** [comment]
![image](https://user-images.githubusercontent.com/16516160/48463364-b77ac100-e816-11e8-92be-3d85d5dfba71.png)
may be storage dealloced something, try it like this?
