### ISSUE TITLE
 Crashed: Cache.AsyncStorage.SerialQueue EXC_BREAKPOINT 0x000000000000defe

### ISSUE THREAD

**Issue by ergunkocak** [hyperoslo/Cache#222]
Hello,

First of all, thanks for great library.

I am having this issue in Fabric for IOS 9 and 10.

Here is the part related to the library:

    5  Cache                          0xecf351 $S5Cache12AsyncStorageC6object6forKey10completionySS_yAA6ResultOyxGctFyAHyAA5EntryVyxGGcfU_ + 160
    6  Cache                          0xecea39 $S5Cache12AsyncStorageC5entry6forKey10completionySS_yAA6ResultOyAA5EntryVyxGGctFyycfU_ + 166
    7  Cache                          0xecfaf7 $S5Cache12AsyncStorageC5entry6forKey10completionySS_yAA6ResultOyAA5EntryVyxGGctFyycfU_TATm + 46
    8  Cache                          0xeceb49 $SIeg_IeyB_TR + 22

**Comment by halonsoluis** [comment]
Hi @ergunkocak ..did you managed to figure it out the reason for this crashes?
