### ISSUE TITLE
Support for Xcode 10.2 beta

### ISSUE THREAD

**Issue by gabors** [hyperoslo/Cache#233]
Noticed that Cache framework does not build in Xcode 10.2 beta 2.

Fails with 
error: Bus error: 10

**Comment by gabors** [comment]
@hyperoslo-services Is this repo still being maintained?
I don't see any activity since October 2018.
Love your product and use it in a number of Swift apps, would be a shame for this repo to die.

**Comment by tettoffensive** [comment]
@gabors I'm wondering the same.

**Comment by aehlke** [comment]
Failing in beta 3 with `error: Illegal instruction: 4`

**Comment by SuperY** [comment]
@gabors @tettoffensive @aehlke  
A temporary plan:
Build Setting -> Swift Compiler -> Optimization Level ->Release -> [-Osize]

**Comment by Igor-Palaguta** [comment]
Updating MD5 to recent fixed issue for me in Xcode 10.2 https://github.com/hyperoslo/Cache/pull/236

**Comment by gabors** [comment]
> Updating MD5 to recent fixed issue for me in Xcode 10.2 #236

Thank you I'll give it a try!

**Comment by gabors** [comment]
@Igor-Palaguta updating MD5 worked great with Xcode 10.2 beta 4 as well. 
спасибо!

**Comment by lucasromanomr** [comment]
Suporte for Xcode 10.2 release with Carthage.

**Comment by enoelboostmi** [comment]
Any update on this?

**Comment by DaveMcKraken** [comment]
![Screen Shot 2019-03-26 at 6 13 14 PM](https://user-images.githubusercontent.com/33290261/55041487-db36ea80-4ff2-11e9-9549-a30171aac49c.png)

Changing to `No Optimization` on Debug/Test worked for me

**Comment by philCc** [comment]
supports Xcode 10.2 release? with cocoapods

**Comment by philCc** [comment]
> Suporte for Xcode 10.2 release with Carthage.

*** Building scheme "Cache-iOS" in Cache.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/phil/Documents/jenkins/workspace/kyiOS-build/Project/Ky_iOS/Carthage/Checkouts/Cache/Cache.xcodeproj -scheme Cache-iOS -configuration Release -derivedDataPath /Users/phil/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/Cache/5.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/63/1z5qdfb53ls7z34xq53399h40000gn/T/Cache SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/phil/Documents/jenkins/workspace/kyiOS-build/Project/Ky_iOS/Carthage/Checkouts/Cache)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/63/1z5qdfb53ls7z34xq53399h40000gn/T/carthage-xcodebuild.lBKthf.log

**Comment by olcayertas** [comment]
> ![Screen Shot 2019-03-26 at 6 13 14 PM](https://user-images.githubusercontent.com/33290261/55041487-db36ea80-4ff2-11e9-9549-a30171aac49c.png)
> 
> Changing to `No Optimization` on Debug/Test worked for me

`Optimize for Size [-Osize]` also works.

**Comment by philCc** [comment]
@olcayertas yes, it works, but, if you use cocoapods or carthage, how to setting?

**Comment by DaveMcKraken** [comment]
With @olcayertas comment, I found that this post install script in my podfile did the trick:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Cache pod does not accept optimization level '-O', causing Bus 10 error. Use '-Osize' or '-Onone'
    if target.name == 'Cache'
      target.build_configurations.each do |config|
        level = '-Osize'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = level
        puts "Set #{target.name} #{config.name} to Optimization Level #{level}"
      end
    end
  end
end
```

**Comment by philCc** [comment]
@DaveMcKraken  it works for me, thank you

**Comment by lucasromanomr** [comment]
Has anyone managed to make it work with the carthage?

**Comment by yiyuan-liaoqiang** [comment]
it works for me,666

**Comment by yiyuan-liaoqiang** [comment]
@DaveMcKraken it works for me,666
