### ISSUE TITLE
Cache Run Wrong

### ISSUE THREAD

**Issue by iosoracle** [hyperoslo/Cache#242]
Xcode Version 10.2 (10E125)

Cache  
Command faild due to signal: Bus error: 10

**Comment by jnckjian** [comment]
What to do in the end

**Comment by jnckjian** [comment]
> Xcode Version 10.2 (10E125)
> 
> Cache
> Command faild due to signal: Bus error: 10

What to do in the end

**Comment by clouddevil** [comment]
Get the same error (Bus error: 10) when build for release.

![image](https://user-images.githubusercontent.com/9379791/55940954-dfe1dc80-5c49-11e9-9470-201033595343.png)

Workaround: Switch Compilation Mode from whole module to incremental.

![image](https://user-images.githubusercontent.com/9379791/55940986-ecfecb80-5c49-11e9-85e0-1f95664ba9b4.png)

**Comment by shuoli84** [comment]
Same as #238

**Comment by evermeer** [comment]
for now you could add the following to your pod file:

```
post_install do |installer|
   installer.pods_project.targets.each do |target|
      if target.name == 'Cache'
         target.build_configurations.each do |config|
            config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
            puts "Set #{target.name} #{config.name} to Optimization Level -Osize"
         end
      end
   end
end
```

**Comment by lucasromanomr** [comment]
But for carthage?...

**Comment by evermeer** [comment]
@lucasromanomr The PR with the fix should be merged or you could manually set the opimazation level to -Osize

**Comment by evermeer** [comment]
@lucasromanomr You could also use github "Igor-Palaguta/Cache" "560f00a9a9549db161ca70d96eed74fc580b03e3" for Carthage until this project gets updated
