### ISSUE TITLE
crash on insert key

### ISSUE THREAD

**Issue by zfpan1981** [hyperoslo/Cache#250]
![497d-905d](https://user-images.githubusercontent.com/7984517/61992939-8639dc80-b097-11e9-9522-628be83301f5.png)

**Comment by zfpan1981** [comment]
set<String> is not thread safe？

**Comment by canaksoy** [comment]
same problem (urgent)

**Comment by cmcnab** [comment]
I think this is the same as issue #249 and I'm seeing it too.

**Comment by malonehedges** [comment]
@3lvis this issue still exists

**Comment by 3lvis** [comment]
Thanks for writing up, are there steps to reproduce this one?
