### ISSUE TITLE
Is there any plan to release support for Swift 5.1?

### ISSUE THREAD

**Issue by bandhavivinay90** [hyperoslo/Cache#253]

**Comment by halonsoluis** [comment]
Looks like this library has been abandoned, no updates in one year 🤔

**Comment by raissetto** [comment]
valid alternatives?

**Comment by halonsoluis** [comment]
I'm thinking on migrating to Realm what I was achieving with this one, and of course, I'll need to also find an alternative for Imaginary ...so far, KingFisher is the best candidate

**Comment by gabors** [comment]
I forked an older version of this repo a while ago (before all the new changes that required generic storage for every type of Codable) and it works fine with Xcode 11.1+ and Swift 5.1 with full SwiftPM support in several production apps.

**Comment by gabors** [comment]
For image caching I really like https://github.com/kean/Nuke

**Comment by stevapple** [comment]
I’ve planned to switch to [onmyway133/EasyStash](https://github.com/onmyway133/EasyStash) for data persistence. Also support `Codable` and `SPM`, and the APIs are similar.

**Comment by helloMrTom** [comment]
老铁，什么时候能更新一下Swift5啊

**Comment by sandammeer** [comment]
You can use our fork with swift 5.1 support https://github.com/thepeaklab/Cache.git

**Comment by hlc0000** [comment]
一个使用Swift 5编写的轻量级iOS通用缓存库SwiftlyCache，如果有兴趣可以试试https://github.com/hlc0000/SwiftlyCache/

**Comment by NikKovIos** [comment]
Take a look at https://github.com/Haneke/HanekeSwift and https://github.com/onevcat/Kingfisher.
