### ISSUE TITLE
Value of type 'Image' has no member 'cache_toData'

### ISSUE THREAD

**Issue by bratherem** [hyperoslo/Cache#255]
```
let toData: (Image) throws -> Data = { image in
      return try image.cache_toData().unwrapOrThrow(error: StorageError.transformerFail)
    }
```

Was show error:
Value of type 'Image' (aka 'UIImage') has no member 'cache_toData'

**Comment by ralfebert** [comment]
Same here, this occurs when used as a Swift Package Manager package, where it doesn't include the iOS source folder.
