### ISSUE TITLE
Error linking on XCode 12

### ISSUE THREAD

**Issue by FerFrassia** [hyperoslo/Cache#265]
<unknown>:0: error: module map file '/Users/Library/Developer/Xcode/DerivedData/Vidit-fovalhoxxhzfpnawqjbgydwxidfv/Build/Products/Debug-iphonesimulator/Cache/Cache.modulemap' not found

**Comment by norbdev** [comment]
> compiling for iOS 8.0, but module 'Cache' has a minimum deployment target of iOS 9.0

**Comment by 3lvis** [comment]
Fix incoming!
