### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by andreseko** [hyperoslo/Cache#269]
Hey Guys

You have to update the documentation the usage let storage = Storage().... the version 6.0.0 ask for a Storage<Hash, any> and haven't any example how to init that.

Thank you.

**Comment by piemonte** [comment]
hey @andreseko i'm doing this:

https://github.com/piemonte/Poly/blob/master/Sources/PolyCache.swift#L35-L46

**Comment by 3lvis** [comment]
Hi @andreseko, I added it to the changelog https://github.com/hyperoslo/Cache/releases/tag/6.0.0

but will make sure to update the docs as well
