### ISSUE TITLE
Insecure Storage: Lacking Data Protection

### ISSUE THREAD

**Issue by Shakihassan** [hyperoslo/Cache#270]
On line 81 of DiskStorage.swift, the method setObject:_:forKey:expiry:() writes data to a file lacking sufficient encryption settings.The identified method writes data to a file lacking sufficient encryption settings.

Note : Reported by Fortify on demand

**Comment by 3lvis** [comment]
Thank you for reporting, any suggestions on what we can do to improve it?

**Comment by 3lvis** [comment]
Closing, reason outdated issue.
