### ISSUE TITLE
Rename Result in Result.swift to avoid conflicts with Swift.Result

### ISSUE THREAD

**Issue by colinhumber** [hyperoslo/Cache#271]
As the `Result` type is built into Swift now, this can be removed from the codebase to prevent conflicts with the `Swift.Result`.

**Comment by 3lvis** [comment]
Probably better to rename it to CacheResult before removing it.

**Comment by colinhumber** [comment]
That's very true. I neglected to look closely at the signature and `Cache.Result` is only generic over the type in `value`, whereas `Swift.Result` is generic over both `Success` and `Failure`.

**Comment by agarmash** [comment]
What's wrong with Swift.Result having 2 generic parameters? On the contrary, it gives the ability to pass custom error types. Also, it already has `map<NewSuccess>(_ transform: (Success) -> NewSuccess) -> Result<NewSuccess, Failure>` method, which is manually implemented in CacheResult.
The only issue is a public API change, from `.value` to `.success` for the successful case.

**Comment by 3lvis** [comment]
@agarmash Are you pitching to Replace right? If it doesn't create any conflicts I'm happy merge your PR.

**Comment by agarmash** [comment]
@3lvis Exactly. If the described API change is acceptable, I'm happy to make a PR

**Comment by 3lvis** [comment]
@agarmash Happy to review your PR, go for it!

**Comment by 3lvis** [comment]
Merged :D
