### ISSUE TITLE
Fix unstable test

### ISSUE THREAD

**Issue by agarmash** [hyperoslo/Cache#274]
`SyncStorageTests.testRemoveAll` fails time-to-time, seems that it's dependent on some other test

<img width="1552" alt="Screenshot 2020-10-30 at 17 11 08" src="https://user-images.githubusercontent.com/9504693/97715893-fc679300-1ad3-11eb-9ce9-392c3cfc66d9.png">

**Comment by 3lvis** [comment]
I've seen this as well... we should find a way to fix it rather than removing it.

**Comment by 3lvis** [comment]
I've seen this as well. Probably sharing the same data layer than other tests.
