### ISSUE TITLE
expiry does not work !

### ISSUE THREAD

**Issue by expll** [hyperoslo/Cache#281]
setObject  and DiskConfig MemoryConfig  all setted！  but it does not work any one

**Comment by expll** [comment]
let diskConfig = DiskConfig(name: "SnakeRead", expiry: .seconds(1))
        let memoryConfig = MemoryConfig(expiry: .seconds(1), countLimit: 10, totalCostLimit: 10)

        let storage = try? Storage<String, String>(
          diskConfig: diskConfig,
          memoryConfig: memoryConfig,
          transformer: TransformerFactory.forCodable(ofType: String.self)
        )
        
        var cache:String? = try? storage?.object(forKey: "url")
        if cache?.count ?? 0 > 0 {
            if let obj = [SNBar].deserialize(from: cache, designatedPath: "results") {
                self.data = obj as! [SNBar]
                callBack()
            }
        } else {
            HTTP.GET(url,
                     parameters: ["limit":10],
                     headers: SNPCH.lcheader()) { response in
                if response.statusCode == 200 {
                    if let obj = [SNBar].deserialize(from: response.text, designatedPath: "results") {
                        self.data = obj as! [SNBar]
                        callBack()
                        
                        // 缓存
                        try?SNCache.shared.storage.setObject(response.text!, forKey: "url", expiry: .seconds(1))
                    }
                }
            }
        }

**Comment by 3lvis** [comment]
Any chance to get some help here? I don't have the bandwidth to fix issues but I can take some time to review them and merge them.

**Comment by zeqinjie** [comment]
+1   version 5.3

**Comment by loseleo** [comment]
you should call 'storage?.removeExpiredObjects()' before get the cache ,it's worked for me

**Comment by 3lvis** [comment]
Closing, reason outdated issue.
