### ISSUE TITLE
Can't use on Xcode 12

### ISSUE THREAD

**Issue by marcusziade** [hyperoslo/Cache#282]
I’m unable to run it on Xcode 12. I can’t run carthage bootstrap without it failing. I’ve gotten errors saying that the 5.3 version of that framework was compiled using a slightly older version of the Swift compiler than the one I’m using.
I’m not sure what to do to resolve the issue

When I run carthage bootstrap with the Xcode location set to Xcode 12.2 the build just fails with a long string indicating the location of the thing on disk 

`Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/marcusziade/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/Cache/5.3.0/Build/Intermediates.noindex/ArchiveIntermediates/Cache-iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Cache.framework/Cache /Users/marcusziade/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/Cache/5.3.0/Build/Products/Release-iphonesimulator/Cache.framework/Cache -output /Users/marcusziade/Dev/project-ios/Carthage/Build/iOS/Cache.framework/Cache
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/bp/vyktptpd7wz9t7rhpth57qw40000gn/T/carthage-xcodebuild.xvsKP5.log`

I’ve tried changing the framework version to 6.0 which is the latest, but that wont install either. When I change the target version to 6.0 in the cartfile and do carthage update I get this:

`Ryzentosh:project-ios marcusziade$ carthage update
*** Fetching Cache
*** Checking out Cache at "6.0.0"
*** xcodebuild output can be found in /var/folders/bp/vyktptpd7wz9t7rhpth57qw40000gn/T/carthage-xcodebuild.pQq4rA.log
*** Downloading Cache.framework binary at "Cache — 6.0.0"
***  Skipped installing Cache.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1) and the local version is 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)."
    Falling back to building from the source`

**Comment by 3lvis** [comment]
Thank you for reporting, will have to double check. Intel mac or M1 Mac?

**Comment by marcusziade** [comment]
I'm pretty sure the issue is on my end and in my project. You can probably disregard it. Happy new years

**Comment by 3lvis** [comment]
Closing, reason outdated issue.
