### ISSUE TITLE
Invalid Exclude on XCode 13

### ISSUE THREAD

**Issue by BrettyWhite** [hyperoslo/Cache#296]
Swift is throwing a warning in XCode 13 that 

```swift
targets: [
        .target(
            name: "Cache",
            path: "Source",
            exclude: ["Library/ImageWrapper.swift"]),
```

`ImageWrapper.swift` is not found.

I am able to use the lib using SwiftPM and the 6.0.0 release, but it will not compile by selecting master, which may be a separate issue.

**Comment by isaacressler** [comment]
There is a PR for this #290.

**Comment by si-hartmann** [comment]
This project seems pretty dead?

**Comment by 3lvis** [comment]
Closing, reason outdated issue.
