### ISSUE TITLE
[Feature request] SPM Support

### ISSUE THREAD

**Issue by ameedsayeh** [hyperoslo/Cache#299]
Thanks for the great package!
it would be great if we can get it via Swift Package Manager 😄

**Comment by akirmse** [comment]
I wanted to bump this, as many projects are leaving Cocoapods and moving to SPM.  I migrated a very simple repo to SPM and it wasn't too hard:

https://github.com/drtimcooper/LatLongToTimezone/commit/b3e68efb56d08f3baea57f3043145e7ab75568fe
https://medium.com/justeattakeaway-tech/migrating-to-swift-package-manager-efb9d2f61ddf

**Comment by 3lvis** [comment]
Does it work?
