### ISSUE TITLE
can you support cache to keychain

### ISSUE THREAD

**Issue by phpmaple** [hyperoslo/Cache#30]
if this, cache can always storage even delete App

**Comment by zenangst** [comment]
Hey @phpmaple what kind of things where you thinking of caching in the keychain ?

**Comment by phpmaple** [comment]
I think that can storage disk ,whether storage sync to keychain or icloud, then can be awesome

**Comment by zenangst** [comment]
I don't really follow? If you want to store things on iCloud, would it be more appropriate to do that using Apples cloud storage API?

**Comment by zenangst** [comment]
I'm gonna go ahead and close this one because of the lack of response but feel free to re-open and add some more info to this issue 😎
