### ISSUE TITLE
How to clear  all cache of whole app

### ISSUE THREAD

**Issue by Najamus** [hyperoslo/Cache#300]
i can't be able to create Storage shared object its throw an error id not add transformer, 

My Disk name is same only change transformer while saving different model in cache. 

Now i want to clear all cache of app while user tap on clear cache without knowing all transformer type. 

i'm trying but not find a way how to do that. 

kindly share some details how can i achieve it 

Thanks

**Comment by 3lvis** [comment]
Closing, reason outdated issue.
