### ISSUE TITLE
removeResourceObjects sortedFiles should return time1 < time2

### ISSUE THREAD

**Issue by ywz364kf** [hyperoslo/Cache#302]
let sortedFiles = objects.sorted {
      if let time1 = $0.resourceValues.contentModificationDate?.timeIntervalSinceReferenceDate,
        let time2 = $1.resourceValues.contentModificationDate?.timeIntervalSinceReferenceDate {
        return time1 > time2
      } else {
        return false
      }
    }
    this will remove recent file, generally speaking should remove the file which older not the recent

**Comment by SymbolStar** [comment]
any update???

**Comment by 3lvis** [comment]
@SymbolStar Hi, this project isn't actively supported and currently is 100% community driven, if you send us a PR with a fix I am happy to review it.

**Comment by 3lvis** [comment]
Closing, reason outdated issue.
