### ISSUE TITLE
Disk cache failed to save object with specific cache string

### ISSUE THREAD

**Issue by DikeyKing** [hyperoslo/Cache#309]
When use directory as cache key, disk cache just fail

This key dose not work

`/private/var/mobile/Containers/Data/Application/BBFA132393-27C1-4A50-903420-B5742173983BF8A/Documents/14231/2022-11-03_11-30-28.zip`

And this works

`2022-11-03_11-30-28.zip`

This may be a bug?

**Comment by Ali-Zameen89** [comment]
Any fix for this?

**Comment by 3lvis** [comment]
Strange, I can't think of an immediate fix but if you find one I'm happy to review your Pr.

**Comment by 3lvis** [comment]
Closing for lack of follow up.
