### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by telip007** [hyperoslo/Cache#31]
Can I cache objects from custom class, for example `class Car{
// methods...
}` ?

**Comment by zenangst** [comment]
Hey @telip007, yeah it supports custom objects, they just need to conform to the `Cachable` protocol as stated in the README. There is also an example in the playground.

https://github.com/hyperoslo/Cache/blob/master/Playgrounds/CustomCache.playground/Contents.swift#L25-L48

https://github.com/hyperoslo/Cache#cachable-protocol

Hope this helps.
