### ISSUE TITLE
Question: What happens if `totalCostLimit` cannot be honored?

### ISSUE THREAD

**Issue by gmoraleda** [hyperoslo/Cache#312]
Let's say I set some value for my MemoryConfig `totalCostLimit` that cannot be honored (or no limit at all).
Will the app receive a memory warning? 
When does the library start cleaning objects from the memory cache?

Thanks a lot in advance!

**Comment by 3lvis** [comment]
I believe @onmyway133 might have the answer to this.

**Comment by 3lvis** [comment]
Closing for lack of answer.
