### ISSUE TITLE
Please update version

### ISSUE THREAD

**Issue by charleyzhu** [hyperoslo/Cache#313]
Please update the version, SPM can only use maximum version 6.0.0

**Comment by 3lvis** [comment]
Would you mind sending a Pull Request? Happy to review it!

**Comment by vincentneo** [comment]
> Would you mind sending a Pull Request? 

Swift Package Manager (SPM)'s package versioning is based on git release tags so I don't think anyone can deal with that via a PR.

**Comment by 3lvis** [comment]
New release tag created!
