### ISSUE TITLE
Storage increases very fast on iOS 17+

### ISSUE THREAD

**Issue by Samigos** [hyperoslo/Cache#319]
I've been using this library for quite some time now and it works great! The thing is that as soon as I updated to iOS 17, the disk storage my app takes increases very much for each video that gets cached! I also tested on iOS 17.4 and same thing happened! It actually reached 10GBs of storage! On iOS 16+ it usually takes 200 - 300 MBs.

Any ideas?

(I've tried repo versions 6.0.0 & 6.1.0)

**Comment by 3lvis** [comment]
Going from 300 MB to 10 GB is for sure quite the jump. Honestly, I don't know what is happening.

**Comment by Samigos** [comment]
Turns out it's a global iOS 17 issue with storage
[link](https://forums.developer.apple.com/forums/thread/737831)

Any idea on how to tackle such an issue? I'm considering using the MemoryConfig for storage, but I think it's not possible to have Storage with Memory only?

**Comment by 3lvis** [comment]
Quite unfortunate, I hope Apple fixes it soon.

**Comment by 3lvis** [comment]
> I'm considering using the MemoryConfig for storage, but I think it's not possible to have Storage with Memory only?
This is correct! Memory will keep it alive as long as the app is alive.
