### ISSUE TITLE
Latest Release 6.2.0 isn't available on Cocoapod

### ISSUE THREAD

**Issue by kaungsoe** [hyperoslo/Cache#320]
Hi, 

The latest Release 6.2.0 isn't available on Cocoapod. Only 6.0.0 is available. Anyway to update? I wouldn't mind submitting a PR for this changes, please let me know how to update.

Thanks.

**Comment by gsbernstein** [comment]
Should the readme be updated to reflect the fact that `pod 'Cache'` isn't sufficient to get updates?

**Comment by 3lvis** [comment]
Readme updated!

https://github.com/hyperoslo/Cache/?tab=readme-ov-file#installation

**Comment by 3lvis** [comment]
@caosuyang In your Podfile use this instead.

pod 'Cache', :git => 'https://github.com/hyperoslo/Cache.git'
