### ISSUE TITLE
i'm hope obtain cache data synchronously

### ISSUE THREAD

**Issue by arden** [hyperoslo/Cache#33]
cache.object("data") { (data: NSData?) in
  // Use your NSData object
}

now, obtain cache data is async. but i'm hope to sync like this.

let data = cache.object("data")

did you have any plan to support it?

**Comment by vadymmarkov** [comment]
@arden We are actually considering this feature for the next major release. We'll keep you posted 😉

**Comment by onmyway133** [comment]
@vadymmarkov or there will be a function in Sugar that convert async to sync ? 😬

**Comment by vadymmarkov** [comment]
@onmyway133 To do that you'll probably need an access to the dispatch queue, right?

**Comment by vadymmarkov** [comment]
or you mean some crazy stuff like semaphore? 😄
