### ISSUE TITLE
About Config class conflicts

### ISSUE THREAD

**Issue by arden** [hyperoslo/Cache#37]
ours project have a Config class,  and you Cache project have a Config class also, 
now there have some conflicts both Config class,
What should I do？

let config = Cache.Config(
    // Your front cache type
    frontKind: .Memory,
    // Your back cache type
    backKind: .Disk,
    // Expiry date that will be applied by default for every added object
    // if it's not overridden in the add(key: object: expiry: completion:) method
    expiry: .Date(NSDate().dateByAddingTimeInterval(7 \* 24 \* 60 \* 60 \* 60)),
    // Maximum size of your cache storage
    maxSize: 10000)

use Cache.Config also not.

**Comment by dagio** [comment]
Same problem here

**Comment by onmyway133** [comment]
@arden @dagio Thanks for raising it out. We're aware of it, too. The reason is we have `Cache` as a class, so it steals the `Cache` namespace.

**Comment by dagio** [comment]
@onmyway133 The `Cache` class name seems legit. Maybe renaming the pod to have a more unique name without the conflict could be a solution. That could be in a 2.0 release the keep semver ?

**Comment by vadymmarkov** [comment]
@onmyway133 @zenangst @RamonGilabert I think it's a bit late to rename the pod. Maybe it would be easier to rename `Cache` class to something like `StrictCache`?

**Comment by dagio** [comment]
Wether you change the pod name or the class name, you will introduce a BC break. I would have rename the pod name to something like : CacheKit, CacheFramework, SimpleCache, ...
Cache class name is perfectly valid. On the other hand the framework name should be unique.
Unfortunately there is no easy way to solve this...
