### ISSUE TITLE
Question: Completion handlers are called in the original threads

### ISSUE THREAD

**Issue by Hengyu** [hyperoslo/Cache#40]
The `completion`s in class which conforms to `StorageAware` is called in its original thread. For example, the `completion` of a `add` method is called in `writeQueue`; the `completion` of a `object` method is called in `readQueue`. 
If the cache read/write is associated, we should call `dispatch_async(dispatch_get_main_queue())` every the UI needs update.
Maybe put `completion` in main thread will be better?

for example:
change this

```
public func remove(key: String, completion: (() -> Void)? = nil) {
    dispatch_async(writeQueue) { [weak self] in
      guard let weakSelf = self else {
        completion?()
        return
      }

      weakSelf.cache.removeObjectForKey(key)
      completion?()
    }
  }
```

to

```
public func remove(key: String, completion: (() -> Void)? = nil) {
        dispatch_async(writeQueue) { [weak self] in
            guard let weakSelf = self else {
                dispatch_async(dispatch_get_main_queue()){
                    completion?()
                }
                return
            }

            weakSelf.cache.removeObjectForKey(key)
            dispatch_async(dispatch_get_main_queue()){
                completion?()
            }
        }
    }
```

**Comment by vadymmarkov** [comment]
@Hengyu It was intentional from the beginning, so that it's up to developer to dispatch in needed queue in the completion callback. But could give another look at it and reconsider. What do you guys think @hyperoslo/ios

**Comment by zenangst** [comment]
I think it would be hard to define a silver bullet for this, there might be some causes where you don't want it to go back to the main queue. I think it is better to let the developer decide which queue should be used and when, just like @vadymmarkov stated.

**Comment by dreymonde** [comment]
Hey! I’m just the user of **Cache** and want to share an opinion. In my point of view, the current approach is fine. Dispatching to the main queue «by default» is pretty bad move if you’re using `NSOperation`s, for example. And there are a lot of other situations when you want to handle your object in the background, not interrupting main thread. So I think that writing `dispatch_async(dispatch_get_main_queue())` is not that bad after all. 😄

**Comment by zenangst** [comment]
I agree with @dreymonde, we will stick with the current approach for now.
