### ISSUE TITLE
2.3 branch

### ISSUE THREAD

**Issue by navisingh** [hyperoslo/Cache#50]
The only change required to support swift 2.3 is
    let alpha = CGImageGetAlphaInfo(CGImage!)
instead of
    let alpha = CGImageGetAlphaInfo(CGImage)
in the file UIImage+Cache.swift

**Comment by zenangst** [comment]
Hey @navisingh, I've created a branch and asked the author of #52 to point it to that branch instead.
This is the PR in question - https://github.com/hyperoslo/Cache/pull/52

**Comment by zenangst** [comment]
#52 was just merged so if you point it to use `swift-2.3` you should be fine 😎

**Comment by ikovalisko** [comment]
@zenangst would you mind releasing `swift-2.3` branch? I want to use Cache in my private pod, but it's not possible to specify a branch in `podspec`'s dependency.

**Comment by ikovalisko** [comment]
@zenangst I've noticed a 2.0 release with Swift 3.0 support. Is it possible to make a maintenance release of 1.x for Swift 2.3?
