### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by v-silin** [hyperoslo/Cache#53]
Hi.

Do you have any plans about swift 3?

Best regards.

**Comment by zenangst** [comment]
Hey @v-silin, yeah we are planning on support Swift 3 for all our OSS. We are in the process of converting all repositories. We will keep you posted as soon as we have a branch that you can use :)

**Comment by zenangst** [comment]
Hey @v-silin, we are not quiet ready to merge `swift-3` into `master` but you can use it today by configuring your dependency manager to point to that branch;

**Cartfile**
```
github "hyperoslo/Cache" "swift-3"
```

**Podfile**
```
pod 'Cache', :git => 'https://github.com/hyperoslo/Cache', :branch => 'swift-3'
```
