### ISSUE TITLE
what time will be support swift3?

### ISSUE THREAD

**Issue by Mosaics** [hyperoslo/Cache#54]

**Comment by onmyway133** [comment]
@Mosaics Hi, there is no official support for Swift 3 yet, but there is an ongoing development in Swift 3, you may want to take a look https://github.com/hyperoslo/Cache/commits/swift-3

**Comment by Mosaics** [comment]
@onmyway133 how can i use it?

**Comment by zenangst** [comment]
@Mosaics just point to that branch in your Cartfile or Podfile.

**Cartfile**
```
github "hyperoslo/Cache" "swift-3"
```

**Podfile**
```
pod 'Cache', :git => 'https://github.com/hyperoslo/Cache', :branch => 'swift-3'
```
