### ISSUE TITLE
Question on threading

### ISSUE THREAD

**Issue by MingLoan** [hyperoslo/Cache#57]
I checked the code and saw that memory cache will process in another thread asynchronously as well. Is there any option to process memory cache in synchronously?

**Comment by vadymmarkov** [comment]
@MingLoan According to the current framework design, every type of cache is meant to be async. But you can use [SyncCache](https://github.com/hyperoslo/Cache#type-safe-cache) to process it synchronously.

**Comment by zenangst** [comment]
@MingLoan Hope this answered your question, closing this for now.

**Comment by MingLoan** [comment]
thanks
