### ISSUE TITLE
Swift 3 support please... again

### ISSUE THREAD

**Issue by mjhassan** [hyperoslo/Cache#62]
I saw two issue on swift 3 support, which are [#53](https://github.com/hyperoslo/Cache/issues/53) and [#54](https://github.com/hyperoslo/Cache/issues/54).
But I don't see and Swift-3 branch in code branch. Or if I try 

    pod 'Cache', :git => 'https://github.com/hyperoslo/Cache', :branch => 'swift-3'

it failed to install the pod, with following errors

> [!] Error installing Cache
[!] /usr/bin/git clone https://github.com/hyperoslo/Cache /var/folders/rz/ys35b0nd0j56kxrb7ghlyk9c0000gn/T/d20161109-3430-asduqn --template= --single-branch --depth 1 --branch swift-3

> Cloning into '/var/folders/rz/ys35b0nd0j56kxrb7ghlyk9c0000gn/T/d20161109-3430-asduqn'...
warning: Could not find remote branch swift-3 to clone.
fatal: Remote branch swift-3 not found in upstream origin

can you please upload the swift 3 branch?

**Comment by zenangst** [comment]
Hey @mjhassan, `master` is now built with Swift 3.
This should work for you:

```ruby
pod 'Cache', '~> 2.0'
```

Let us know how it goes 😎

**Comment by mjhassan** [comment]
It works now. Thank you for helping me.
Can you please add retirements section in `Readme`, so one might not get misunderstood, as me, over Swift version? Thanks again.

**Comment by zenangst** [comment]
@mjhassan glad to hear it mate 😎 What we tend to do is to make releases that clearly state that there are breaking changes or, as in this case, have migrated the library to Swift 3. (https://github.com/hyperoslo/Cache/releases)

We also have a badge to indicate language support which is pointing to `master`.

<img width="898" alt="screen shot 2016-11-09 at 19 47 35" src="https://cloud.githubusercontent.com/assets/57446/20150298/7c48917e-a6b5-11e6-95d6-d02bc889d87d.PNG">

**Comment by mjhassan** [comment]
My bad, I should have seen that badge. Thank you for pointing that out :)

**Comment by zenangst** [comment]
@mjhassan don't worry mate, cheers and enjoy `Cache` 😎
