### ISSUE TITLE
Doesnt save to disk

### ISSUE THREAD

**Issue by zdenektopic** [hyperoslo/Cache#63]
Hello,

I am using your cache for images. The type-safe one. However it doesnt persisted cached images to object. When I restart the app, the image is not there :( I am using `.disk` for back cache.

```
let config = Config(frontKind: .memory, backKind: .disk)
cache = Cache<UIImage>(name: SnapshotManager.CACHE_NAME, config: config)
```

**Comment by zenangst** [comment]
Hey @zdenektopic, could you share a code snippet to show us how you save the images using `Cache` ?

**Comment by zdenektopic** [comment]
Sure:
```
    func get(forPanel panel: Panel, cacheOnly: Bool = false, completion: @escaping GetCompletionHandler) -> Request {
        let req = Request()
        
        cache.object(panel.id, completion: { [weak self] (object) in
            if let image = object, req.cancelled == false {
                completion(image)
            } else if cacheOnly == false {
                guard let _self = self, req.cancelled == false else {
                    return
                }
                
                _self.save(forPanel: panel, completion: { image in
                    if req.cancelled {
                        return
                    }
                    
                    completion(image)
                })
            } else {
                if req.cancelled {
                    return
                }
                completion(nil)
            }
        })
        
        return req
    }
    
    func save(forPanel panel: Panel, completion: @escaping GetCompletionHandler) -> Request {
        let req = Request()
        panel.webView.createSnapshot { (snapshot) in
            self.cache.add(panel.id, object: snapshot)
            if req.cancelled == false {
                completion(snapshot)
            }
        }
        
        return req
    }

```

**Comment by zdenektopic** [comment]
any ideas?

**Comment by onmyway133** [comment]
@zdenektopic How does your `snapshot` conform to `Cachable`?

**Comment by zdenektopic** [comment]
Its UIImage. That should conform by default, right?

**Comment by aasatt** [comment]
Same issue here. 

If I set front to memory and back to disk. I can load the object immediately after adding it. The next time the app is launched the object cannot be loaded.

If I set front to disk, it then fails to load even immediately after adding it.

I am using the type safe SyncCache. 

Any solution?

**Comment by ened** [comment]
1. What are you using for the cache Key? I mistakenly used the absolute path of a file within my documents directory, while I should have used the relative path within it. Reason is that on every app install during development, the absolute path to the document directory changed (should be documented somewhere).

2. My initial thought was a misconfiguration on the `maxSize` and `maxObjects` parameters to Cache.Config, but any of those work for me:

``` swift
static var imageCache = Cache<UIImage>(name: "thumbnailImageCache")

static var imageCache = Cache<UIImage>(name: "thumbnailImageCache", 
    config: Config(frontKind: .memory, backKind: .disk))

static var imageCache = Cache<UIImage>(name: "thumbnailImageCache", 
    config: Config(frontKind: .memory, backKind: .disk, maxSize: 30720, maxObjects: 100))
```

**Comment by biogerm** [comment]
having the same issue here. Memcache works fine, I can save and pull out the value from cache. However if I try to load the item from disk, it fails. When I look into the content saved on the disk, it's the same for all of them: 8 byte, with same content c0fb 8027 9b7f 0000

**Comment by biogerm** [comment]
I'm on Xcode 8.3 swift 3.1, but it was the same before upgrading, I guess it was 8.2 3.0.2

**Comment by biogerm** [comment]
btw I am caching a customised class, pretty much like in the demo, a User class, just with more values. I'm also using the same DefaultCacheConverter as in the example. Since saving and loading from memory works fine, I guess it's not the converter's fault.

**Comment by biogerm** [comment]
Solved the problem using NSCoding and NSKeyedUn/archiver un/archiveObject/Data() with manual implementation of fields...

**Comment by vadymmarkov** [comment]
Is it still a problem? Does it happen on simulator or on device?

**Comment by s1ddok** [comment]
happens to me as well, everytime app is re-launched, I can't retrieve objects from Cache

**Comment by vadymmarkov** [comment]
@s1ddok Did you try to use document directory?
```swift
    let documentsPath = NSSearchPathForDirectoriesInDomains(
      .documentDirectory, .userDomainMask, true
    ).first!

    let cache = SpecializedCache<UIImage>(
      name: "Image",
      config: Config(
        expiry: .never,
        cacheDirectory: "\(documentsPath)/JSONStorage"
      )
    )
```

**Comment by s1ddok** [comment]
Exactly how I’m doing this

**Comment by s1ddok** [comment]
It works for strings/jsons for me, but doesnt work for Coding structs

**Comment by s1ddok** [comment]
@vadymmarkov I'm fighting with your lib for a week already, and can't understand what goes wrong. It encodes and saves my objects successfully, but it can't unarchive them afterwards.

![](https://i.gyazo.com/10c6c95edfedcd8233a2dc691a6b031a.png)

**Comment by zgosalvez** [comment]
@s1ddok I noticed the same issue. I'm using the default config with SpecializedCache with CacheArray on a class implementing Coding. Here are weird things that I noticed.

1. The cache is stored in disk, in a folder with the name of the SpecializedCache, w/o the `no.hyper.Cache` prefix.
2. The cache successfully decodes from front storage (memory) during same application life-cycle, but cannot decode from back storage (disk) after application restart.

I'm already looking for alternative cache libraries. 😞

**Comment by siyavash4812** [comment]
@zgosalvez were you able to find an alternative?  I have the exact same problem

**Comment by zgosalvez** [comment]
@siyavash4812 [Awesome Cache](https://github.com/aschuch/AwesomeCache)

**Comment by siyavash4812** [comment]
@zgosalvez I changed from Awesome Cache to this library because that wouldn't save my items either. As long as I am inside the app, cache works fine but when i close the app and open again there is no cache

**Comment by Jerome1210** [comment]
same issue.. Any update?

**Comment by Jerome1210** [comment]
I solve this issue and found that is not a bug in `Cache` but my code :(
At first, I have a class like this

```swift
class Merchant: NSObject, Cachable, NSCoding {
    
    static var current: Merchant?
    
    var id: String = ""
    var name: String = ""
    var locale: String = ""
    var currency: String = Locale.current.currencyCode!
    var shippingFee: Double = 0.0
    
    typealias CacheType = Merchant
    
    static func decode(_ data: Data) -> Merchant? {
        let merchant = NSKeyedUnarchiver.unarchiveObject(with: data) as? Merchant
        return merchant
    }
    func encode() -> Data? {
        let data = NSKeyedArchiver.archivedData(withRootObject: self)
        return data
    }
    
    func encode(with aCoder: NSCoder) {
        aCoder.encode(mId, forKey: #keyPath(mId))
        aCoder.encode(name, forKey: #keyPath(name))
        aCoder.encode(locale, forKey: #keyPath(locale))
        aCoder.encode(currency, forKey: #keyPath(currency))
        aCoder.encode(shippingFee, forKey: #keyPath(shippingFee))
    }

    required convenience init?(coder aDecoder: NSCoder) {
        guard let id = aDecoder.decodeObject(forKey: #keyPath(mId)) as? String,
            let name = aDecoder.decodeObject(forKey: #keyPath(name)) as? String,
            let locale = aDecoder.decodeObject(forKey: #keyPath(locale)) as? String,
            let currency = aDecoder.decodeObject(forKey: #keyPath(currency)) as? String,
            let shippingFee = aDecoder.decodeObject(forKey: #keyPath(shippingFee)) as? Double else {
            return nil
        }
        self.init(json:[:])
        self.mId = id
        self.name = name
        self.locale = locale
        self.currency = currency
        self.shippingMethod = ShippingMethod(rawValue: shippingMethod)!
        self.shippingFee = Double(shippingFee)!
    }

```

And I found out in 
`let id = aDecoder.decodeObject(forKey: #keyPath(mId)) as? String`
`let shippingFee = aDecoder.decodeObject(forKey: #keyPath(shippingFee)) as? Double`
The `id` and `shippingFee` will be nil, even my cached value is not nil nor 0
So the guard will fail and return a nil object from cached.

I fix this issue by replace `var id` -> `var mId`. I think this issue was caused since `id` is a reserved keyword in ObjC and this could make bug when NSKeyedArchiver/NSKeyedUnarchiver try to encode/decode object.

and I fix shippingFee by turning it to String when encoding, and turning back to Double when decoding. eg: 
```swift
    func encode(with aCoder: NSCoder) {
        aCoder.encode(String(shippingFee), forKey: #keyPath(shippingFee))
    }
    required convenience init?(coder aDecoder: NSCoder) {
        guard let shippingFee = aDecoder.decodeObject(forKey: #keyPath(shippingFee)) as? String else {
            return nil
        }
        self.shippingFee = Double(shippingFee)!
    }
```

I know this solution is kinds of like a workaround, but it work well.
Hope this comment will help someone.

**Comment by onmyway133** [comment]
@Jerome1210 Glad that you solved it
