### ISSUE TITLE
Not compatible with swift 3

### ISSUE THREAD

**Issue by abdulelah1** [hyperoslo/Cache#64]
When i install Cache pod or update the pods i should convert the syntax to Swift 3
( this problem starts after i install Cache pod )

**Comment by zenangst** [comment]
Hey @abdulelah1, which version are you using? Version `2.0.0` has been converted to Swift 3. Maybe you just need to do `pod update Cache`. Try and check what your pod lock file states, it is probably just pointing to an older version.

**Comment by abdulelah1** [comment]
i'm using cache version 2.1.1 
<img width="262" alt="screen shot 2016-11-22 at 4 33 18 pm" src="https://cloud.githubusercontent.com/assets/21056071/20525970/04ccc840-b0d3-11e6-804b-d13db729c6dc.png">

**Comment by zenangst** [comment]
Have you tried removing the `Pods` folder and tried `pod install` again?

**Comment by abdulelah1** [comment]
I'm just tried nothing changed

**Comment by zenangst** [comment]
This seems super odd to me. One thing that you could try is to add the following to your `Podfile`.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0.1'
    end
  end
end
```

That has worked for us in the past.
Let us know how it goes.

**Comment by JohnSundell** [comment]
Closed due to inactivity. Let us know if this issue is still relevant and we'll re-open 😄
