### ISSUE TITLE
Parameter maxSize

### ISSUE THREAD

**Issue by kubatruhlar** [hyperoslo/Cache#66]
What is the expected unit for `maxSize `, bits? Documentation did not say a thing about units, it would be great to add some.

**Comment by ened** [comment]
Bytes. See `DiskStorage.swift`, line 260 for details:

```
      if let fileSize = file.resourceValues[URLResourceKey.totalFileAllocatedSizeKey] as? NSNumber {
```

Comparison is based on bytes.

**Comment by vadymmarkov** [comment]
👍

**Comment by georgbachmann** [comment]
May I hijack this issue and ask if or how the `maxSize` is working? I set it to 10.000.000 (~ 10MB) but still, the folder on my mac where I cache to is well over that limit.
I set a breakpoint to the only place where `maxSize` is used and it's never called...
Is there a bug or am I just miss-understanding the usage?
I'd like to limit my cache to let's say 10MB and data should be removed by FiFo...
