### ISSUE TITLE
Encrypted Cache?

### ISSUE THREAD

**Issue by damianesteban** [hyperoslo/Cache#68]
Hello hyperoslo. You guys and gals make some truly fantastic libraries - I love them.

Anyway, do you know if it is possible to encrypt a cache (specifically Cache)?

**Comment by zenangst** [comment]
Interesting idea! This is definitely something that would a really neat feature for the future. Feel free to make a PR if you have some ideas. We would gladly review it, cheers 🍻

**Comment by damianesteban** [comment]
Cool, I definitely will.  Thank you 👍

**Comment by ened** [comment]
@damianesteban Would this be based on Data Protection for the .diskStrategy? https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/StrategiesforImplementingYourApp/StrategiesforImplementingYourApp.html#//apple_ref/doc/uid/TP40007072-CH5-SW21

**Comment by damianesteban** [comment]
That's one of the possibilities that I'm exploring.  I've also been looking at implementing encryption with [RNCryptor](https://github.com/RNCryptor/RNCryptor) (or something similar)

The use case is a HIPAA compliant app and SHA-256 is recommended for PHI (actual PHI would rarely be stored in the cache but because there is a possibility it needs to be encrypted).

Do you have any recommendations?
