### ISSUE TITLE
use NSCoding instead of Cachable

### ISSUE THREAD

**Issue by evermeer** [hyperoslo/Cache#69]
It would be nice if NSCoding was used instead of Cachable.
I think that In most cases it's easier to add to your own objects.
It also has support for changed class definition.

Besides that it would be nice if backStorage could be set to StorageAware.none so that we can prevent writing sensitive data.

**Comment by evermeer** [comment]
I'm now playing around with adding Cache support to a project where I use https://github.com/evermer/EVReflection
The extension below will add it to every data object that I have.


```
extension EVReflectable: Cachable {
    /**
     Creates an EVObject from NSData
     
     - Parameter data: Data to decode from
     - Returns: An optional EVObject
     */
    public static func decode<T>(_ data: Data) -> T? where T: EVObject {
        return NSKeyedUnarchiver.unarchiveObjectWithData(data) as? T
    }
    
    /**
     Encodes an EVObject to NSData
     - Returns: Optional NSData
     */
    public func encode() -> Data? {
        return NSKeyedArchiver.archivedDataWithRootObject(self)
    }
}
```

With that extension it's also easy to add Cache support to every object that has NSObject as it's base class. You could for instance add Cache support to every Realm or object using:

```
extension Realm.Object: EVReflectable { }

extension NSManagedObject: EVReflectable { }
```

But I still think that using NSCoding instead of Cachable would be a better solution.

**Comment by vadymmarkov** [comment]
I think `Cachable` protocol is more flexible, because it's easy to use it together with structs and enums. And you can still use `NSCoding` if it's needed.

**Comment by evermeer** [comment]
True, but now that Swift 4 is coming, you could change it to Codable. Here are some helper functions that you could 'borrow' https://github.com/evermeer/Stuff#codable

**Comment by onmyway133** [comment]
@evermeer Hi, your wish comes true. `Cache` now supports `Codable` out of the box https://github.com/hyperoslo/Cache/releases/tag/4.0.0

**Comment by evermeer** [comment]
Great to hear!
I will give it a test drive
