### ISSUE TITLE
Cache.swift can not compile w/ Xcode 8.3 beta

### ISSUE THREAD

**Issue by ened** [hyperoslo/Cache#73]
Xcode 8.3 beta will complain about override statement on these methods:

```
  public override func add(_ key: String, object: T, expiry: Expiry? = nil, completion: (() -> Void)? = nil) {
  public override func object(_ key: String, completion: @escaping (_ object: T?) -> Void) {
```

Xcode 8.2 is fine with it. Probably a Swift compiler upgrade so it should be helpful to check it soon.

**Comment by kevin-hirsch** [comment]
Hey @ened I face the same issue, did you find a workaround in the meantime?

**Comment by ened** [comment]
Unfortunately no. Switched back to 8.2 of the moment.

**Comment by kevin-hirsch** [comment]
It seems that adding `<T: Cachable>` to the function directly is working like:

```swift
public override func add<T: Cachable>(_ key: String, object: T, expiry: Expiry? = nil, completion: (() -> Void)? = nil)
```

**Comment by bradhowes** [comment]
I submitted a pull request for with the change above, but it failed to compile in Travis. :(

**Comment by ened** [comment]
Actually looks like a compiler bug.. applying your patch fixes it on 8.3, but breaks 8.2.

**Comment by ened** [comment]
``` swift
  /**
   Adds passed object to the front and back cache storages.

   - Parameter key: Unique key to identify the object in the cache
   - Parameter object: Object that needs to be cached
   - Parameter expiry: Expiration date for the cached object
   - Parameter completion: Completion closure to be called when the task is done
   */
  #if swift(>=3.1)
    public override func add<T: Cachable>(_ key: String, object: T, expiry: Expiry? = nil, completion: (() -> Void)? = nil) {
      super.add(key, object: object, expiry: expiry, completion: completion)
    }
  #else
    public override func add(_ key: String, object: T, expiry: Expiry? = nil, completion: (() -> Void)? = nil) {
      super.add(key, object: object, expiry: expiry, completion: completion)
    }
  #endif

  /**
   Tries to retrieve the object from to the front and back cache storages.

   - Parameter key: Unique key to identify the object in the cache
   - Parameter completion: Completion closure returns object or nil
   */
  #if swift(>=3.1)
    public override func object<T: Cachable>(_ key: String, completion: @escaping (_ object: T?) -> Void) {
      super.object(key, completion: completion)
    }
  #else
    public override func object(_ key: String, completion: @escaping (_ object: T?) -> Void) {
      super.object(key, completion: completion)
    }
  #endif
```

That doesn't seem right?

**Comment by dpassage** [comment]
FYI, I filed this issue as a bug - rdar://30880621 / https://bugs.swift.org/browse/SR-4184 - and the response was that the original code should not have been accepted. The Radar has been closed, although the swift.org bug is still open.

I think the basic issue is that `BasicHybridCache` is a non-generic class with generic methods; the upshot is that it provides no guarantee that all cached items are the same type. Whereas `Cache` is a generic class, meaning that it does provide that guarantee.

Maybe the solution is to make `BasicHybridCache` generic? I'm not sure how that would affect the overall design of the library.

**Comment by lm2s** [comment]
Regarding this issue, has anyone had this problem after updating Xcode to 8.3?

```
private var imageCache: Cache<UIImage> = Cache<UIImage>(name: kImageCacheKey)
func test() {
        imageCache.object("key") { (cached) in
        }
}```

Generates error:
`Generic parameter 'T' could not be inferred`

<img width="882" alt="captura de ecra 2017-03-28 as 14 51 43" src="https://cloud.githubusercontent.com/assets/221489/24408730/5ec2aed6-13c6-11e7-8b9f-a73c70b3e43e.png">

**Comment by JohnSundell** [comment]
@lm2s you need to add type information to `cached` so that the compiler knows that type you're looking for (since it cannot be inferred from the context), like this:

```swift
func test() {
    imageCache.object("key") { (cached: UIImage?) in

    }
}
```

**Comment by vadymmarkov** [comment]
This issue was fixed https://github.com/hyperoslo/Cache/pull/74 and then https://github.com/hyperoslo/Cache/pull/80
