### ISSUE TITLE
Can we add an API to get the current size of a cache being used?

### ISSUE THREAD

**Issue by seonman** [hyperoslo/Cache#76]
As described in the title, can we add an API to get the current size of a cache?

I want to see how much disk space is being used for a cache.
Even with the maxSize and expiry setting, some caches seem to keep growing, even though it sometimes decreased a little, and then grow again.

I am calling clearExpired() when my app starts, but it is no good.

Thanks.

**Comment by vadymmarkov** [comment]
Yes, I think it should be possible 😉

**Comment by vadymmarkov** [comment]
@seonman This feature will be included in the next major version 😉

**Comment by seonman** [comment]
@vadymmarkov Thank you so much! Looking forwarding to the new API.
