### ISSUE TITLE
Remove StorageFactory, front and back cache configuration.

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Cache#79]
We have `StorageFactory`, but I feel it just adds more complexity to the public API. How often do we have extra cache types or set disc cache as a front cache? It's always memory cache backed up with disc cache. I propose to remove this factory and simplify config:

```swift
let config = Config(
  // Expiry date that will be applied by default for every added object
  // if it's not overridden in the add(key: object: expiry: completion:) method
  expiry: .date(Date().addingTimeInterval(100000)),
  // Maximum size of your cache storage
  maxSize: 10000)
```

What do you guys think? @zenangst @onmyway133 @JohnSundell ?

**Comment by zenangst** [comment]
The case that you describe seems super edge-casy :) I would vote for removing it.

**Comment by x-hovo-x** [comment]
Hi guys,

would it solve issue [#77](https://github.com/hyperoslo/Cache/issues/77) ?

**Comment by onmyway133** [comment]
I've never used or heard of `StorageFactory`, so I vote to remove it too 😄
