### ISSUE TITLE
Cache found in back storage isn't set on front storage

### ISSUE THREAD

**Issue by kirmanie** [hyperoslo/Cache#83]
After a memory warning causes the clearing of the front storage (memory), all future cache requests will resolve from the back storage (disk), never the front storage. 

This is because, after resolving from back storage, we don't set front storage with the results of back storage. Is this by design?

**Comment by vadymmarkov** [comment]
It's by initial design, yes. But it can be improved.

**Comment by kirmanie** [comment]
@vadymmarkov thanks! Don't know much about the vision and direction of the project but took a crack at this issue anyway in [this PR](https://github.com/hyperoslo/Cache/pull/84). Would be interested in hearing your thoughts.

**Comment by kirmanie** [comment]
Closing this issue because it was resolved in [this PR](https://github.com/hyperoslo/Cache/pull/84) which got merged in.
